### ISSUE TITLE
UI - Make search tool results in "Tool catalog" page more reliable.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#116]
I am not able to reliably get tool search to return tools I am looking for.

In case of searching for "digital ocean" , no tool gets returned

<img width="929" alt="Screenshot 2024-08-11 at 1 40 21 PM" src="https://github.com/user-attachments/assets/7326c70f-0f47-4290-b5a7-7070caea3853">

When searching for "eks" , I see only `Eksctl` returned and not "Amazon EKS"
<img width="945" alt="Screenshot 2024-08-11 at 1 43 00 PM" src="https://github.com/user-attachments/assets/8169b6e6-a32f-40a2-bb9c-3ca3b695f556">
 
I am not able to get search results even for "Amazon EKS".
<img width="894" alt="Screenshot 2024-08-11 at 1 44 52 PM" src="https://github.com/user-attachments/assets/59c5cb78-d5a5-483e-8bc8-006d521aad3e">

Other times like this , I have seen it work as expected (with contains search criteria and search being case insensitive)
<img width="572" alt="Screenshot 2024-08-11 at 1 44 22 PM" src="https://github.com/user-attachments/assets/845b0039-4417-4f4d-9a9e-ff5f6f40a499">

**Comment by sangee2004** [comment]
When testing with the latest build - `9d4616691` , I am able to see the search results in `Tool Catalog` page fetch the right entries , but the name with which they get displayed is very misleading.


This is true for many entries in the featured list which have read/write versions of the tools.

Searching for mail will show 2 entries "Manage" and "Read" which is very confusing
<img width="1226" alt="Screenshot 2024-09-04 at 4 10 50 PM" src="https://github.com/user-attachments/assets/397d3001-adab-47a8-9fe0-da85e1e47b51">



This is when slack is searched: 

https://github.com/user-attachments/assets/0dc2dfb5-1fdf-411c-a5c3-8c81b6ddb165

**Comment by sangee2004** [comment]
Search in the tool catalog page which gets launched from "Edit Assistant" page lets us search for other tools that are not in the feature list . This should not be the case -https://github.com/gptscript-ai/desktop/issues/248#issuecomment-2330339732.

**Comment by cjellick** [comment]
We're addressing this by completely removing tool site search from the app.

The only piece that was concerning me was this:
> When I searched for internet , i got duckduckgo entry which should not be presented ? This repo is archived,readonly and private.

but i cannot reproduce it

**Comment by sangee2004** [comment]
When searching for `internet` we get only `Answers From The Internet` now.

Closing this issue since issue mentioned in https://github.com/gptscript-ai/desktop/issues/116#issuecomment-2330303837 and https://github.com/gptscript-ai/desktop/issues/116#issuecomment-2330354636 should be addressed with theremoving tool site search from the app.
