### ISSUE TITLE
UI - Need "Back", "Close" options when navigating between pages.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#117]
In general it would be nice to have  "Back", "Close" options when navigating between pages.

Currently the 1 place were I really miss having a Back", "Close" option is in "Edit Assistant" view.

If I am in "Edit Assistant" view and wish to quit this screen , I have to hit "Build" option which is already highlighted to get back to "My Explorer" page from edit view.

**Comment by StrongMonkey** [comment]
A finish button is added in `Edit Assistant` page.

**Comment by sangee2004** [comment]
We now have a `Finish` button in `Edit Assistant` page.Would it be better to have an "x" instead to close this page similar to what we have in "Edit Tool" page for consistency ?

@cjellick I wanted to confirm if we are good with the `finish` button and if there is more we would like to follow up as part of this issue before i close this bug.

**Comment by cjellick** [comment]
We are going to change it slightly. See my most recent UX changes post in Slack.

**Comment by cjellick** [comment]
This is now how i want it - a Back and Reload chat button

**Comment by sangee2004** [comment]
We have "Back" and "Refresh Chat" button in Edit assistant page.
