### ISSUE TITLE
Include the name of the gptscript in the chat session view.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#127]
**Steps to reproduce the problem:**
1. Launch UI using - `GPTSCRIPT_CHAT_UI_TOOL=github.com/gptscript-ai/ui@v2 gptscript --ui`

2. Execute the any script.

Currently there is no way to tell which gptscript is being executed once the chat session view is launched.

It would be good to have the name of the  gptscript  included in this view.

**Comment by sangee2004** [comment]
Tested with electron app - Version 0.10.0-rc3 

We now have the name of the assistant included in the chat view.
When we enter an existing thread , we are always out at the bottom on the conversation.  I need to scroll back to the top of the conversation to see the Assistant name. 
We should be able to keep that as a title bar which should be always present?

**Comment by cjellick** [comment]
Yes, we want to have the title bar pinned AND we want more information in it
