### ISSUE TITLE
Text in confirmation window should be wrapped 

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#130]
gptscript version v0.0.0-dev-ac679cd0-dirty

**Steps to reproduce the problem:**
1. Launch gptscript in UI mode using - `gptscript --ui --disable-cache`
2. Execute the following script
```
Tools:  github.com/gptscript-ai/gpt4-v-vision, github.com/gptscript-ai/dalle-image-generation, sys.download, sys.chat.finish, sys.exec
description: This is a chatbot for image and vision tools which can read and write to local file system.
chat: true
This is a chatbot. Finish the chat when users type bye or quit.
```

3. Enter the following chat message - `Generate an image of cow and download it in cowimage.png`
4. Notice that text for download confirmation overflows.

<img width="1058" alt="Screenshot 2024-06-13 at 2 52 46 PM" src="https://github.com/gptscript-ai/gptscript/assets/122560863/561d7822-9ace-4345-8c14-bfa2fbaa8b53">

**Expected Behavior:**
Text in confirmation window should be wrapped

**Comment by sangee2004** [comment]
This issue is still seen when testing with Version `0.10.0-rc2 `

Confirm prompt is presented as this:
<img width="722" alt="Screenshot 2024-08-13 at 5 02 13 PM" src="https://github.com/user-attachments/assets/2ab11a86-7dbb-4f6e-a35f-8abd5cf1eef1">

 There is a horizontal scroll bar in the prompt field that is not visible unless  user tries to scroll to right. This is still not visible fully.
<img width="716" alt="Screenshot 2024-08-13 at 5 02 19 PM" src="https://github.com/user-attachments/assets/83ce215e-c569-4539-84d8-c059b661f191">

 There is a horizontal scroll bar that appears just above the chat message that is not visible unless user tries to scroll to right after which the whole message appears.
<img width="690" alt="Screenshot 2024-08-13 at 5 02 29 PM" src="https://github.com/user-attachments/assets/8a052e44-33d9-4738-a6e7-9f59ff4947de">

Can this experience be made better? May be wrap the tool name in such cases ?

**Comment by cjellick** [comment]
@g-linville added wrapping

![Image](https://github.com/user-attachments/assets/dd1a5f4e-2629-401b-9202-0148037cd1c0)

**Comment by sangee2004** [comment]
Tested with electron build -  `d7b8724e17c0d5dc`

Text in confirmation window is wrapped as expected.

![Image](https://github.com/user-attachments/assets/44890019-abcd-4c0e-8f78-09013a53c204)
