### ISSUE TITLE
Knowledge tool gets into a loop of trying to fetch the right file and fails eventually hitting the maximum context length.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#134]
Version -  0.10.0-rc2 (0.10.0-rc2)

**Steps to reproduce the problem:**
1. Launch chat with default Acorn Desktop Assistant.
2. Using " Add knowledge" , add 2 files - (Travel and diet pdf in my case)
3. Asked question  - "what can I have in empty stomach" about information in  diet pdf , for which it gave me the answer from internet tool.
4. Then I asked question about information in  travel pdf  - "what is my travel plan for day 8" , for which is fetched information from my travel pdf as expected.
5. Tried to ask the same question from step 3, but this time I asked it to "Can you look up my diet plan doc to find out what can I have in empty stomach "
<img width="841" alt="Screenshot 2024-08-12 at 8 06 26 PM" src="https://github.com/user-attachments/assets/65201cd2-a6a6-4503-ad77-ed5bd5fc5580">

So i provided the actual file name after which it goes in continuous loop and finally failed with maximum context length is 128000 tokens. exceeded error. 

https://github.com/user-attachments/assets/dcfcfa25-ad02-4b8b-ab3d-0e60a937c0f6

<img width="874" alt="Screenshot 2024-08-12 at 7 54 05 PM" src="https://github.com/user-attachments/assets/3526cf3a-90f6-416f-b114-9e5e243dd8dc">

**Comment by cjellick** [comment]
@sangee2004 please atttach the pdfs here

**Comment by sangee2004** [comment]
Tested with electron build from  commit id -`731700663e`

I am still seeing the knowledge tool having problems with being able to fetch data from MyFeb12.dpf file. 

I see the following error 

![Image](https://github.com/user-attachments/assets/477b59b2-8278-4d14-bf0d-6a72b9c5353a)


I have shared the files used for testing with @StrongMonkey .

**Comment by cjellick** [comment]
@sangee2004 can you retest this? I think the latest round of fixes to knowledge may have fixed this

**Comment by sangee2004** [comment]
Tested with electron build from commit id -`731700663e`

When following the steps mentioned in the issue , I am still able to reproduce the issue with Knowledge tool not being able to work in the diet plan pdf even after asking it to use it by providing the name of the document. But i am not seeing the calls go into a continuous loop and trying and failing which resulted in context length exceeding.

**Comment by cjellick** [comment]
Ok, the isue title and description are very much about the continuous loop. Can you either update the title and description to get rid of that part or close this and open a new issue?

**Comment by sangee2004** [comment]
Logged the following issue to track the current behavior seen - https://github.com/gptscript-ai/desktop/issues/320
Closing this issue.
