### ISSUE TITLE
UI - Provide a way to show all the tools used in the chat threads.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#141]
~Currently in the chat view , I am not able to tell with what assistants the threads were initially launched with.
Right now, I would be able to get this info if I select the thread and go to the very first message from the assistant were its name is provided which is very inconvenient.~

_Edit: The above is coverd in #65. I am keeping this around for just the tools bit below_

Also it would be very helpful to show the list of tools this thread is currently using (tools that came from the assistant and the the dynamically added tools ).

**Comment by cjellick** [comment]
The assistant name part is cover in #65. I am editing this to just be about tools

**Comment by cjellick** [comment]
This is in

**Comment by sangee2004** [comment]
Tested with electron build - `a8d8c5c39b3d`

All the features requested for in this issue is available.
