### ISSUE TITLE
Having multiline description results in assistants getting saved incorrectly and is not usable.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#146]
Version 0.10.0-rc2 (0.10.0-rc2)

**Steps to reproduce the problem:**
1. Create an assistant with multiline description 
<img width="624" alt="Screenshot 2024-08-13 at 1 55 42 PM" src="https://github.com/user-attachments/assets/78dc7095-eb70-42fe-b08d-22eb198285de">

2. Edit the assistant . Notice that instruction is incorrect and tool settings are lost.
<img width="595" alt="Screenshot 2024-08-13 at 1 57 54 PM" src="https://github.com/user-attachments/assets/5e5a2ef4-4e0f-4756-b403-6ae12a9334d4">

3. Get out of edit mode without changing anything.
4. Chat with the assistant.
Notice that no input field is provided for chat messages to be entered.

**Comment by thedadams** [comment]
Description field should not allow multiple lines.

**Comment by thedadams** [comment]
PR: https://github.com/gptscript-ai/desktop/pull/220

**Comment by sangee2004** [comment]
Tested with electron build  with commit id -`523bf344b9e` . We are not allowed to enter multi line description when creating assistants.
