### ISSUE TITLE
Exiting a thread without confirming to a tool call prompt, results in the thread erroring out "authorize called multiple times for same ID" for the same message being made in any thread. 

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#148]
Version 0.10.0-rc2 
**Steps to reproduce the problem:**
1. Chat with Tildy (Acorn Desktop Assistant)
2. Ask any question that involves a tool call like - "who won 2024 superbowl?"
3. When prompted to  allow all calls from the github.com/gptscript-ai/answers-from-the-internet repo , do not take any action.
4. Leave the thread (visit any other thread)
5. Come back to the thread in step 2.
6. Notice that the chat message status shows "in progerss" . But we are able to type a message click on it twice to send the message.
<img width="661" alt="Screenshot 2024-08-13 at 4 49 29 PM" src="https://github.com/user-attachments/assets/8f96b1c0-534f-4b4f-8625-1711a071c067">

7. Ask the same question that involves answers-from-the-internet tool call from step 2 -  "who won 2024 superbowl?"
8. User is presented with the following error message:
<img width="621" alt="Screenshot 2024-08-13 at 4 43 49 PM" src="https://github.com/user-attachments/assets/a8874695-804c-46e7-b6e1-4491e42d5c8d">

9. Start a new chat with Tildy (Acorn Desktop Assistant) and ask the same question -  "who won 2024 superbowl?"
10. User is presented with the following error message:
<img width="621" alt="Screenshot 2024-08-13 at 4 43 49 PM" src="https://github.com/user-attachments/assets/a8874695-804c-46e7-b6e1-4491e42d5c8d">

Once user uses "Restart script" option he can get out of this state.

**Comment by cjellick** [comment]
You can also see this behavior on the Edit Assistant page. 

Here's a avideo of it. You can see it at 0:44:49 of this video or by looking in the transcript for
> Okay, refresh. Dang it. This is a bug. Um, refreshing when it's kind of waiting for a prompt puts it in a bad state.

https://www.loom.com/share/4c46566fc8c5437b93f125c6a87989ae


Steps to repro (roughly, watch the video for better context):
1. In assistant editor, get the chat pane to a state where its prompting you to Allow something
2. make a change to the assistant, like just update the prompt (not sure if this step is necessary)
3. Click the Refresh Chat

The chat pane gets an error that says "authorize called multiple times"

**Comment by thedadams** [comment]
PR: https://github.com/gptscript-ai/desktop/pull/407

**Comment by sangee2004** [comment]
Tested with build - `9d46166`

"authorize called multiple times for same ID" error is not seen when testing both the scenarios tracked in this issue.
