### ISSUE TITLE
Not able to chat with existing threads  after chatting with assistant using other provider (claude ).

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#161]
Version 0.10.0-rc3 

**Steps to reproduce the problem:**
Pre Req - Have few threads from chat with Tildy (or any assistants).
1. Create an assistant with model (in `Advanced`)  as `claude-3-5-sonnet-20240620 from github.com/gptscript-ai/claude3-anthropic-provider`
2. Start a chat using this assistant.
3. I am prompted to enter anthropic key and I am able to get response successfully.
4. Go to any other existing thread and have a chat
Notice that we are presented with this error message:

<img width="700" alt="Screenshot 2024-08-14 at 1 58 19 PM" src="https://github.com/user-attachments/assets/7130b70b-6531-4093-b61a-76c0e57ecfbd">

Restarting also does not get us out of this state.

All existing threads  and new chats show this problem.

I had to delete the claude thread started in step 2 , do manual refresh , quit chat window ( got to Build) and then come back to chat window to have existing threads and new threads start working.

**Comment by g-linville** [comment]
This should be fixed on main now.

**Comment by sangee2004** [comment]
This issue is not seen when testing with commit id - `1eeb6f0161e`
