### ISSUE TITLE
"Something went wrong!" message presented when switching threads when response is still being streamed.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#162]
Electron app version - `0.10.0-rc3`

**Steps to reproduce the problem:**
1. Have multiple chat threads.
2. From one of the threads, initiate a chat message and even before a response is streamed fully click on another thread.

This results in the following page presented to the user:

<img width="1013" alt="Screenshot 2024-08-14 at 3 14 53 PM" src="https://github.com/user-attachments/assets/af6726b4-f6d7-49a6-b967-bae8cba0a5b4">

https://github.com/user-attachments/assets/ede4238a-7e8a-40d3-bde0-1cf688cfab43

**Comment by g-linville** [comment]
Moving this back into Triage and unassigning myself since I have been given other things to do.

**Comment by thedadams** [comment]
PR: https://github.com/gptscript-ai/desktop/pull/407

**Comment by thedadams** [comment]
The above PR fixed this, but I just tested after merging and it is doing something else weird. Will continue to investigate here.

**Comment by thedadams** [comment]
I believe this is the rest of it: https://github.com/gptscript-ai/desktop/pull/412

**Comment by sangee2004** [comment]
Tested with electron build - `54ecc2c`

This issue is not seen anymore.

When I quit the thread when response is still being streamed and when I revisit the same thread , I dont see this chat message/response in this thread. Will follow up on this issue separately.
