### ISSUE TITLE
Improve workflow around oauth process that requires "OK" button 

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#175]
In the oauth flow for tools like outlook , why are we forcing user to click on "ok" after auth url is clicked and authentication is completed, If I dont click "ok" and start asking questions , i get no response. If i click "ok" after this and then ask question no response . The only way for me to get around this is to start a new chat session.

No credential gets saved until I click "ok".  Why is completing the authentication process not sufficient for us to save the credentials in this case?

Can we prevent users from being able to start chatting until the full auth process including clicking on "ok" button is complete?

**Comment by thedadams** [comment]
Once [this](https://github.com/gptscript-ai/desktop/pull/204) PR is merged, the UI will look like this when prompting for credentials.
<img width="1021" alt="Screenshot 2024-08-20 at 12 25 54" src="https://github.com/user-attachments/assets/01145c04-9cdf-4145-9640-7d4c5143612e">

**Comment by sangee2004** [comment]
Tested with electron build `ac04ff0416` 

There is no oauth url exposed in oauth workflow for `slack`, `notion` and `calendar` tools.


![Image](https://github.com/user-attachments/assets/a443361b-17f3-4f6e-b23a-3b1d63fbda3c)
![Image](https://github.com/user-attachments/assets/a68087ae-2783-4c75-aa74-8756cbcd7bf1)
![Image](https://github.com/user-attachments/assets/7a2394e9-188f-4669-a06c-f925226b362b)




But i still see the url exposed for `mail` tool.


![Image](https://github.com/user-attachments/assets/06343745-4855-4239-adde-ce296335d79d)

**Comment by sangee2004** [comment]
After clearing cache and configs for `desktop` and `gptscript`, I am able to see the right right behavior for email tool as well.




![Image](https://github.com/user-attachments/assets/19ce93b9-1b69-45ea-9823-ea242d292573)
