### ISSUE TITLE
Not able to continue to chat in the thread after denying the confirm prompt for running tool call 

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#179]
Electron build from commit id -  `1eeb6f0161e8`

**Steps to reproduce the problem:**
1. Create an assistant with Trello tool call 
2. Chat this is assistant.
3. When presented with following prompt, deny it
<img width="842" alt="Screenshot 2024-08-16 at 10 48 49 AM" src="https://github.com/user-attachments/assets/9bc09879-044a-4731-919f-2051a257173b">
4. Following error is presented to the user:
<img width="858" alt="Screenshot 2024-08-16 at 10 42 20 AM" src="https://github.com/user-attachments/assets/4556d299-6bea-4f4a-9f5e-9b325c36256b">
5. After this we are not able to chat and get any response 
<img width="848" alt="Screenshot 2024-08-16 at 10 43 03 AM" src="https://github.com/user-attachments/assets/22e2d995-64ee-49e2-95f2-c7d1dde1a236">

**Comment by cjellick** [comment]
havent been able to repro. can you retest

**Comment by sangee2004** [comment]
@cjellick I am able to reproduce the issue noted in the bug.

I think what might not have been obvious here is that when I am asked to "Restart Scipt" in step 4 , I am not restarting the script.
I am just asking questions to the LLM which does not involve Trello tool and expected it to succeed which was not the case.




https://github.com/user-attachments/assets/f99be462-3256-4c1c-b694-9115295ff802

**Comment by cjellick** [comment]
Ok. Does this only occurr with trello?

If it is trello specific, im going to deprioritize it as i'll be taking trello out of the catalog because overall it is not very good and not critical to our primary usecase.

**Comment by sangee2004** [comment]
With tools like outlook which has oauth workflows , there is no confirm/deny prompt during the authentication process.
If i choose to not take any action for the sign in process  and start other conversations with LLM , i get the same behavior of not getting any response. 

![Image](https://github.com/user-attachments/assets/812dbb89-e099-4df5-89ee-bd2240a42825)

**Comment by sangee2004** [comment]
Tested with build from  `9d46166919`

This issue is not reproducible anymore. User is not allowed to enter any text when app is waiting for a response to a prompt or confirmation.
