### ISSUE TITLE
`duplicate key value violates unique constraint` error when authenticating with Slack tool.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#182]
Electron built from commit id `59351d72`

**Steps to reproduce the problem:**
1. Start chat with "Tildy" , add slack tool using "Add Tool"
2. Ask a question relating to your slack channel
3. Go thru the auth process and click  the "OK" button .
4. We see the following error being presented to the user in chrome browser:
```
{"error":"failed to create token request challenge: ERROR: duplicate key value violates unique constraint \"o_auth_token_request_challenges_pkey\" (SQLSTATE 23505)"}
```
Note - We are able to chat with slack even when this issue is seen.

**Comment by thedadams** [comment]
PR: https://github.com/gptscript-ai/gateway/pull/11
