### ISSUE TITLE
Should not be allowed to enter messages when waiting for user to respond to a confirmation prompt.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#183]
Electron built from commit id 59351d72

**Steps to reproduce the problem:**

1.Start chat with "Tildy" , add slack tool using "Add Tool"
2. Ask a question relating to your slack channel
3. When confirmation prompt is presented, do not respond.
<img width="727" alt="Screenshot 2024-08-16 at 3 32 57 PM" src="https://github.com/user-attachments/assets/de88d83d-a374-440b-8e54-69e08c0ac66c">

4. Ask another question relating to your slack channel  and click the send button(Which shows in progress state) twice. 
5. This results in message being sent to LLM and another confirmation prompt shows up.
6. Accept the confirmation and we get the response.
7. Now go back to the confirmation prompt in step 3 and accept it.

Notice that the tool call gets stuck forever in calling state:

<img width="766" alt="Screenshot 2024-08-16 at 3 30 20 PM" src="https://github.com/user-attachments/assets/48040741-aa3c-4e1e-a8d9-14e519dc8e95">

**Expected Behavior:**
User should not be allowed to send chat messages in step 4 when waiting for user to respond to a confirmation prompt.

**Comment by thedadams** [comment]
@sangee2004 I am seeing this issue as fixed. Can you test it again?

**Comment by sangee2004** [comment]
Re opening this issue for feedback on following input:

I expected that the user should not be allowed to send chat messages in step 4 when waiting for user to respond to a confirmation prompt . But i understand now that when i click the send button twice , the first one cancels the  previous message and the second click actually sends a new message.

Can we prevent users from being able to go back to confirmation prompt that was unanswered and cancelled and take action on it (this is step 7 in the issue) ? This results in response stuck in "calling tool" state .



In general, Would it be ideal for not allowing users to enter messages when we show the chat state to be in progress ?

![Image](https://github.com/user-attachments/assets/4dac4130-9b6d-4fa1-83ee-cedac0433d55)

**Comment by thedadams** [comment]
Based on other issues that have been logged, the behavior here is changing. When we are waiting for the user to respond to any prompt (confirmation, prompt for credentials, etc), then the chat bar will be disabled. See the screenshot for an example.

<img width="938" alt="Screenshot 2024-09-03 at 12 15 41" src="https://github.com/user-attachments/assets/aa116543-07ca-4c08-b3a2-c4355ba54954">

**Comment by thedadams** [comment]
PR: https://github.com/gptscript-ai/desktop/pull/398

**Comment by sangee2004** [comment]
Tested with electron build -`81ca1d72a2f`

User is not allowed to enter messages when waiting for confirmation prompts or oauth workflows




![Image](https://github.com/user-attachments/assets/e4941551-e2fd-4263-aecc-938b3e844d8f)
![Image](https://github.com/user-attachments/assets/63ae077f-660b-42c4-8f73-dd26945e37f1)
