### ISSUE TITLE
When users leaves a thread without responding to a confirmation prompt , all threads shows the chat state to be in progress.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#184]
Electron built from commit id https://github.com/gptscript-ai/desktop/commit/59351d72bdcd4eab1b1e454c535ae0d965c37fa5

**Steps to reproduce the problem:**
1. Start conversation in any thread and ask about any information that requires a tool call which  results in a confirmation prompt
 
<img width="805" alt="Screenshot 2024-08-16 at 4 03 57 PM" src="https://github.com/user-attachments/assets/0c89936d-9d88-4881-ac2d-2559494dfac3">

2. Leave this thread without responding to the confirmation prompt . 
3. Enter any thread.
4. Notice the chat state shows that it is  in progress.
<img width="792" alt="Screenshot 2024-08-16 at 3 46 58 PM" src="https://github.com/user-attachments/assets/06188399-13bc-40d3-a1bc-aee4487f8d84">

Typing any chat message and clicking enter will do nothing.
User needs to click on the send button twice to get the messages to be sent.

**Expected Behavior:**
Chat state of 1 thread should not be carried to other threads.

**Comment by thedadams** [comment]
Looks like this was fixed by a previous change.

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with electron build - `54ecc2c`
