### ISSUE TITLE
User is prompted for allowing `sys.openapi` calls in tools repos when using outlook mail tool.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#185]
Electron built from commit id https://github.com/gptscript-ai/desktop/commit/59351d72bdcd4eab1b1e454c535ae0d965c37fa5

**Steps to reproduce the problem:**
1. Create an assistant with  outlook mail tool.
2.Start conversation  wit this assistant and ask question about your emails.

Notice that  user is prompted  allowing `sys.openapi` calls in tools repos couple of times:

<img width="751" alt="Screenshot 2024-08-16 at 4 30 22 PM" src="https://github.com/user-attachments/assets/d39ba0ed-5e2b-43e6-9559-4ba943cc70b6">

**Expected Behavior:**
We should be able to auto accept these `sys.openapi` calls

**Comment by g-linville** [comment]
PR is ready for this. I'll move it to Testing once it is merged.

**Comment by g-linville** [comment]
Merged. These confirmation prompts should look much better in the UI now.

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with build - `523bf344`

User is not prompted for allowing sys.openapi calls in tools repos when using outlook mail /calendar tools.
