### ISSUE TITLE
Outlook mail tool added using `Add tool` is not recognized as tool available for chatting .

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#187]
Electron built from commit id https://github.com/gptscript-ai/desktop/commit/59351d72bdcd4eab1b1e454c535ae0d965c37fa5

When I use "Add tool" option to add outlook mail and then ask any email question, I always get this response

```
To get the emails you received in your inbox today, I'll need to access your email account. This typically requires OAuth2 authentication.

Would you like to proceed with setting up the necessary permissions? If so, please provide the name of the email service you are using (e.g., Gmail, Outlook).
```

I had to respond with `Use my existing OAuth2 authentication`. which succeeds sometimes and gets email.
But also seen it fail with the "model is required" error.

I have seen this behavior only when adding outlook in chat using "Add tools".

<img width="799" alt="Screenshot 2024-08-16 at 2 21 38 PM" src="https://github.com/user-attachments/assets/62183544-dcf2-4f54-bb2d-58c39ac8963f">

<img width="779" alt="Screenshot 2024-08-16 at 2 23 51 PM" src="https://github.com/user-attachments/assets/85459485-0336-479c-bd02-4766918527ca">

<img width="697" alt="Screenshot 2024-08-16 at 2 31 58 PM" src="https://github.com/user-attachments/assets/63e9e8c2-cec9-4a89-b4ed-3f7c66b56349">

This issue is not seen when chatting with a assistant that has outlook mail tool.

**Comment by sangee2004** [comment]
Related issue - https://github.com/gptscript-ai/desktop/issues/178

**Comment by g-linville** [comment]
I believe this is now fixed. The confirmation prompts are still broken until I can merge #196, but as soon as I add the tool dynamically, I asked the LLM to list my inbox emails and it was able to do it successfully.

**Comment by g-linville** [comment]
(This likely was fixed when I improved the titles of the Outlook Mail OpenAPI files in [this PR](gptscript-ai/tools#19).)

**Comment by sangee2004** [comment]
I dont see this issue anymore when testing with latest version outlook mail tool.

**Comment by sangee2004** [comment]
@g-linville I am seeing the same behavior again when testing with latest buids

<img width="965" alt="Screenshot 2024-08-20 at 4 43 12 PM" src="https://github.com/user-attachments/assets/d620bd31-e920-4005-b237-e706110f6fd1">

**Comment by g-linville** [comment]
^ That should be fixed now.

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with latest version of electron - `523bf344b9e` and latest versions of the outlook mail tool.
