### ISSUE TITLE
"failed to find remote model gpt-4o"

### ISSUE THREAD

**Issue by githuney** [gptscript-ai/desktop#188]
I'm a newbie here, this is my first post. I thank you in advance for any guidance you might be willing to provide.

When I run this command, it works:

```
echo "List the 5 world capitals that have the largest populations." > capitals.gpt

gptscript capitals.gpt
11:49:38 started  [main]
11:49:38 sent     [main]
11:49:38 ended    [main] [output=1. Tokyo, Japan\n2. Beijing, China\n3. Delhi, India\n4. Jakarta, Indonesia\n5. Manila, Philippines]

OUTPUT:

1. Tokyo, Japan
2. Beijing, China
3. Delhi, India
4. Jakarta, Indonesia
5. Manila, Philippines
```

However, Tildy gives me a "failed to find remote model gpt-4o" error when I run this command:

`sudo npm run dev:electron`

And the output from terminal is:

```
> acorn@v0.10.0-rc3 dev:electron
> electron .

Starting app server with GPTSCRIPT_BIN="node_modules/@gptscript-ai/gptscript/bin/gptscript"
GPTScript config initialized
Config file updated successfully
> Server is ready at http://localhost:3000
> Dev Electron app started at http://localhost:3000
 ○ Compiling / ...
 ✓ Compiled / in 3.5s (4873 modules)
 GET / 200 in 4465ms
 POST / 200 in 676ms
 POST / 200 in 50ms
 POST / 200 in 1417ms
 POST / 200 in 8ms
 POST / 200 in 7ms
 POST / 200 in 4198ms
 POST / 200 in 597ms
 POST / 200 in 11ms
 POST / 200 in 6ms
 POST / 200 in 8ms
 POST / 200 in 585ms
 POST / 200 in 567ms
 POST / 200 in 12ms
 POST / 200 in 12ms
 POST / 200 in 10ms
 POST / 200 in 5ms
```

If anyone can provide some guidance, I would be very grateful. Thank you!

**Comment by thedadams** [comment]
Hi @githuney.

The Desktop app is still under rapid development, so there will be issues like this. Here is what you can do to rectify this right now.
- If you haven't already, clone `https://github.com/gptscript-ai/gptscript`.
- In the cloned `gptscript` directory, run `make build`. This will create a `gptscript` binary at `./bin/gptscript`. You may have to install Go if you haven't do so already.
- Back in the `desktop` directory, `export GPTSCRIPT_BIN=/path/to/gptscript/bin/gptscript`.
- Then run `npm run dev:electron`

**Comment by cjellick** [comment]
Im going to close this issue. feel free to re-open if this doesnt address it
