### ISSUE TITLE
Include `Sys.Time.Now` when adding productive tools.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#190]
When working with tools like outlook and slack, it will be helpful to add `Sys.Time.Now` tool when user adds any of these tools.

I almost always add `Sys.Time.Now` tool when conversing with these tools.

**Comment by thedadams** [comment]
First of two PRs: https://github.com/gptscript-ai/context/pull/6

**Comment by thedadams** [comment]
Second PR: https://github.com/gptscript-ai/tools/pull/24

**Comment by thedadams** [comment]
These changes are ready. However, they are changes to the tools themselves. Therefore, clearing the cache is likely necessary.

**Comment by sangee2004** [comment]
`current-time` context is now added  to outlook mail and calendar tools.
