### ISSUE TITLE
Even with `Sys.Time.Now` tool included in the assistant, it does not get used when chatting with the assistant about time sensitive queries .

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#191]
Electron build with commit id `56cadbd5779acd6ae9ef`

**Steps to reproduce the problem:**

1. Create an assistant with outlook mail  and `Sys.Time.Now`  tool.
2. Chat with the assistant and ask any question that is time sensitive like "list all emails that I received today.
3. Notice that you will get emails are queried for `2023-10-01` 
```
<tool call> runOperationMicrosoftOutlookEmailApi -> {"operation":"me.mailFolders.ListMessages","args":"{\"mailFolder-id\":\"inbox\",\"$filter\":\"receivedDateTime ge 2023-10-01T00:00:00Z and receivedDateTime le 2023-10-01T23:59:59Z\"}"}
```
4. Ask Assistant what today's date is after which  we are able to get correct response for queries relating to today .

<img width="821" alt="Screenshot 2024-08-19 at 10 39 53 AM" src="https://github.com/user-attachments/assets/ebc29326-bb42-4fff-b19e-9836c54d3bb3">

**Expected Behavior:**
 Chatting  with assistant about time sensitive questions should work without having to ask explicitly to LLM to retrieve the current date.

**Comment by thedadams** [comment]
First of two PRs: https://github.com/gptscript-ai/context/pull/6

**Comment by thedadams** [comment]
These changes are ready. However, they are changes to the tools themselves. Therefore, clearing the cache is likely necessary.

**Comment by sangee2004** [comment]
This issue is not seen anymore when working with outlook mail and calendar tools. There is no need for adding `sys.time.now` tool since they are already available as context tool within the outlook mail and calendar tools.
