### ISSUE TITLE
Outlook Calendar - Does not list  some of my meetings possibly because they are recurring meetings.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#192]
Electron build with commit id 56cadbd5779acd6ae9ef

**Steps to reproduce the problem:**

1. Create an assistant with outlook calendar, mail and Sys.Time.Now tool.
2. Ask for current date without which we are able to perform any time sensitive queries - https://github.com/gptscript-ai/desktop/issues/191
3. Ask assistant for - `Meeting invites i have on my calender today` 
```
<tool call> runOperationMicrosoftOutlookCalendarApi -> {"operation":"me.calendar.ListEvents","args":"{\"$filter\":\"start/dateTime ge '2024-08-19T00:00:00-07:00' and start/dateTime le '2024-08-19T23:59:59-07:00'\"}"}
```

I get back only the `1:1` meeting and not the `Standup` meeting which was sent to "Engineering" team which i am a part of. I am shown as being "optional" attendee and I have accepted this recurring meeting invite.

<img width="849" alt="Screenshot 2024-08-19 at 11 39 30 AM" src="https://github.com/user-attachments/assets/8cfbe96b-2088-45a3-bc86-7497d322e9ef">

**Comment by g-linville** [comment]
Calendar tools have been completely revamped. Meetings on shared/group calendars and recurring meetings should show up now.

**Comment by sangee2004** [comment]
Tested with latest Calendar tool.
Able to list recurring meetings (that was not shown previously) successfully now.
