### ISSUE TITLE
Outlook Calendar -Not able to list meetings for a specific date.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#193]
Electron build with commit id https://github.com/gptscript-ai/desktop/commit/56cadbd5779acd6ae9ef9bd4a192b44b8f4d599c

**Steps to reproduce the problem:**

1. Create an assistant with outlook calendar, mail and Sys.Time.Now tool.
2. Ask assistant to all  meetings for a specific date

No meetings are listed:

Tool call made:
<img width="825" alt="Screenshot 2024-08-19 at 11 54 10 AM" src="https://github.com/user-attachments/assets/c3cb12dd-5bfc-4ee8-99ce-68dec5571409">

Meetings I have for this date:
<img width="850" alt="Screenshot 2024-08-19 at 11 56 51 AM" src="https://github.com/user-attachments/assets/e18d7340-a733-46df-99fa-4147e1a16c48">

**Comment by thedadams** [comment]
It's working for me, but only for one-time events (not recurring).

<img width="908" alt="Screenshot 2024-08-21 at 12 05 43" src="https://github.com/user-attachments/assets/2a1709fc-b612-44d8-98b0-d0717213283e">

**Comment by sangee2004** [comment]
I am able to see the meetings being listed as expected for specific dates.
As @thedadams mentioned the issue I was encountering with meetings not being listed is related to not able to list recurring meetings which is tracked in https://github.com/gptscript-ai/desktop/issues/192
