### ISSUE TITLE
Outlook Calendar - Attempting to create a meeting results in being stuck in `getSchemaMicrosoftOutlookCalendarApi.` and make the whole app un usable even after cancelling the call.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#194]
Electron build with commit id https://github.com/gptscript-ai/desktop/commit/56cadbd5779acd6ae9ef9bd4a192b44b8f4d599c

**Steps to reproduce the problem:**

1. Create an assistant with outlook calendar, mail and Sys.Time.Now tool.
2. Ask assistant to create a meeting.
This results in  user getting stuck in "Calling tool getSchemaMicrosoftOutlookCalendarApi..."  call forever

When I tried to interrupt the current conversation and start a new one , i see the following error

<img width="807" alt="Screenshot 2024-08-19 at 12 03 48 PM" src="https://github.com/user-attachments/assets/12e98c1d-5944-4dbb-a26a-4919245adb90">

After this , I am not able to launch new chat with `Tildy` and it gets stuck in "loading assistant" page forever .Encounter the connect error from above in all my existing threads as well.

Only way to get around this problem is quit the app and relaunch it again.

**Comment by sangee2004** [comment]
Following are the errors seen in terminal when testing with latest version - ` ff04c7f31`
```
2024-08-20T18:46:47.255Z [client] [ERROR] TypeError: Cannot set properties of undefined (setting 'error')
2024-08-20T18:46:47.256Z [client] [ERROR] TypeError: Cannot set properties of undefined (setting 'error')
2024-08-20T18:49:02.651Z [server] [ERROR] Error updating GPTScript config: connect ECONNREFUSED 127.0.0.1:50209
2024-08-20T18:54:09.903Z [client] [ERROR] TypeError: Cannot set properties of undefined (setting 'error')
2024-08-20T18:54:09.904Z [client] [ERROR] TypeError: Cannot set properties of undefined (setting 'error')
```

**Comment by g-linville** [comment]
This should be fixed now that I have fully revamped the Calendar tools.

**Comment by sangee2004** [comment]
Tested with latest calendar tool.
Able to create meetings successfully.
I am not able to create a meeting with any content. Will log a new issue to track this.
