### ISSUE TITLE
Outlook Email - Not able to send email 

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#197]
Electron build with commit id https://github.com/gptscript-ai/desktop/commit/56cadbd5779acd6ae9ef9bd4a192b44b8f4d599c

**Steps to reproduce the problem:**

1. Create an assistant with outlook calendar, mail and Sys.Time.Now tool.
2. Start a chat with this assistant and ask  to send an email.

It asks for data type to be set for email content.

<img width="828" alt="Screenshot 2024-08-19 at 2 42 01 PM" src="https://github.com/user-attachments/assets/843e59bd-f197-4f19-90d4-70245f1fe886">

Asking for content type to be set to plain text also does not help

<img width="863" alt="Screenshot 2024-08-19 at 2 52 22 PM" src="https://github.com/user-attachments/assets/e85e9d58-f32a-45c8-abdf-6aa8599a6633">

**Comment by g-linville** [comment]
Fixed by https://github.com/gptscript-ai/gptscript/pull/805

**Comment by sangee2004** [comment]
Tested with gptscript version v0.0.0-dev+a7c8e572

I am able to send emails successfully.
