### ISSUE TITLE
Outlook email - Contents of email is presented in html format by default and is not readable

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#198]
Electron build with commit id https://github.com/gptscript-ai/desktop/commit/56cadbd5779acd6ae9ef9bd4a192b44b8f4d599c

**Steps to reproduce the problem:**

1. Create an assistant with outlook calendar, mail and Sys.Time.Now tool.
2. Start a chat with this assistant and ask it to retrieve the content of the most recent email.

Notice that it retrieves the email content in html format which is not readable.

We need to ask for the email content to be returned in plain text for it to be readable.

<img width="906" alt="Screenshot 2024-08-19 at 3 00 13 PM" src="https://github.com/user-attachments/assets/feec70fd-da05-42a9-b13a-d2eef2401b27">

**Expected Behavior:**
Have the email content set to plain text by default so that the rendered email content is readable.

**Comment by g-linville** [comment]
Solved this one with some simple prompting.

**Comment by g-linville** [comment]
Merged and ready for testing.
