### ISSUE TITLE
Outlook Mail - Not able to get good search results for Mail

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#199]
Electron build with commit id https://github.com/gptscript-ai/desktop/commit/56cadbd5779acd6ae9ef9bd4a192b44b8f4d599c

**Steps to reproduce the problem:**

1. Create an assistant with outlook mail and Sys.Time.Now tool.
2. Start a chat with this assistant and ask it to retrieve the email about some specific subject like - `List all emails received about company offsite` in my case.

Results that are returned are not related to the search query:

<img width="800" alt="Screenshot 2024-08-19 at 3 36 24 PM" src="https://github.com/user-attachments/assets/1343954d-9f61-4590-a5cf-b54c86d6bb29">

Seems like there are 2 different calls being made when I do "Search for mails about  company offsite" Vs "List all mails about Company Offsite" 

`List all mails about Company Offsite` uses the following call with `filter` and provided the correct result:

```
<tool call> runOperationMicrosoftOutlookEmailApi -> {"operation":"me.mailFolders.ListMessages","args":"{\"mailFolder-id\":\"inbox\",\"$filter\":\"contains(subject, 'Company Offsite')\"}"}
```

`Search for mails about  company offsite` uses the following call with `search` and provides a list of email that do not match the search results:
```
<tool call> runOperationMicrosoftOutlookEmailApi -> {"operation":"me.mailFolders.ListMessages","args":"{\"mailFolder-id\":\"inbox\",\"$search\":\"company offsite\"}"}
```

**Comment by g-linville** [comment]
Moving this to testing. I revamped the Outlook Mail tools so now we wrap their SDK instead of using OpenAPI. We are still calling the same underlying search functionality that was used in the example in this issue, but I have generally seen the LLM do a pretty good job of cleaning up the search results and only showing the user relevant ones. There's not really much we could do to improve how Microsoft handles that search parameter.

**Comment by sangee2004** [comment]
Tested with latest electron build - `2fa0a18069`

When testing win the latest version of Outlook Mail tool , I am still not able to get good results when searching for emails.
 I have an email with subject as "company offsite"

I have seen other search queries work though.

![Image](https://github.com/user-attachments/assets/76d56e17-868e-44dd-9a27-92ff7d222353)


![Image](https://github.com/user-attachments/assets/221c226d-8bd7-4301-b0d2-158f2ae55cbf)

**Comment by sangee2004** [comment]
@g-linville I am reopening this issue for looking into the findings from  https://github.com/gptscript-ai/desktop/issues/199#issuecomment-2318802599

**Comment by g-linville** [comment]
This should finally be good now. My latest change removed the pesky `$search` parameter. Now we search only by subject, sender email address, or sender full name.

**Comment by sangee2004** [comment]
Able to search for email with the contents provided in the bug successfully.
