### ISSUE TITLE
Outlook Mail - Search results do not work for dates specified in MM/DD/YYYY format.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#200]
Electron build with commit id https://github.com/gptscript-ai/desktop/commit/56cadbd5779acd6ae9ef9bd4a192b44b8f4d599c

**Steps to reproduce the problem:**

1. Create an assistant with outlook mail and Sys.Time.Now tool.
2. Start a chat with this assistant and ask it to retrieve the email for a specific date MM/DD/YYYY format like `8/13/2024` 
Notice that no matches are returned.

When we ask the same question for the same date in words like `August 13th 2024` , matched emails are returned.

<img width="983" alt="Screenshot 2024-08-19 at 4 20 20 PM" src="https://github.com/user-attachments/assets/4f29f8a3-2271-4542-be49-5f82d177a15b">

<img width="991" alt="Screenshot 2024-08-19 at 4 20 26 PM" src="https://github.com/user-attachments/assets/74cb7191-f726-4f7f-8dfc-5769e3d1c5bf">

The tool calls made in both cases seem to be the same , but one returns results and other does not.

<img width="731" alt="Screenshot 2024-08-19 at 4 24 31 PM" src="https://github.com/user-attachments/assets/7c10196b-407d-409b-afad-58f201b342d5">

<img width="714" alt="Screenshot 2024-08-19 at 4 22 48 PM" src="https://github.com/user-attachments/assets/4ed72da7-646d-404c-a38d-c2d88ecff165">

**Comment by thedadams** [comment]
@sangee2004 You probably didn't receive any email messages in 2004. Can you double-check that wasn't the problem?

**Comment by sangee2004** [comment]
This is my bad. I am able to get mails to be fetched as expected when date is specified in mm/dd/yyyy format.
