### ISSUE TITLE
"Assistant not found..." error seen when trying to chat with my assistants listed in "+" option in chat view.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#206]
Electron build with commit id `ac04ff04166`

**Steps to reproduce the problem:**
Pre Req - Create new assistants which are private.
1. Launch chat view.
2. Use "+" option and select any of your assistants that you own which is private .
User is presented with the following message:

<img width="1066" alt="Screenshot 2024-08-20 at 4 11 59 PM" src="https://github.com/user-attachments/assets/4d271772-3705-482d-9b8b-b83f2ba74919">

Note - If I make the assistant public then I dont see this problem.

**Comment by cjellick** [comment]
can you retest?

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with latest builds - `a8d8c5c39b3d5`
