### ISSUE TITLE
Incorrect Assistant name for the threads started using "+"  option in chat view with public assistants.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#208]
Electron build with commit id `ac04ff04166`

**Steps to reproduce the problem:**
Pre Req - Create new assistants which are public.
1. Launch chat view.
2. Use "+" option and select any of your assistants that you own which is public and start chating.

Notice that the Assistant name for this thread is shown as `Tildy`

This issue will also be shown when you try to chat with any of the featured assistants from the list.

**Comment by cjellick** [comment]
Appears to be fixed

https://www.loom.com/share/6570be75be5a4841b95d77bbde856133

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with latest build from `d7b8724e1`.
