### ISSUE TITLE
Enhance Add tool experience

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#216]
discussed out of band...details to come

**Comment by cjellick** [comment]
reassigning to @ryanhopperlowe

**Comment by sangee2004** [comment]
@cjellick @ryanhopperlowe  Could you provide an outline of what has been addressed as part of this issue?

**Comment by cjellick** [comment]
Yeah @ryanhopperlowe please do that

**Comment by ryanhopperlowe** [comment]
While editing an assistant and after opening the Tools Accordian, you'll see three buttons under the Equipped tools list
1. "Featured Tools" opens the same tool catalog found on the chat "/" menu
2. "Add Tool via URL" opens the same dialog found on the chat "/" menu
3. "Create a Tool" remains unchanged

**Comment by ryanhopperlowe** [comment]
@sangee2004 

The Add tool catalog has been updated In both the chat ("/") menu and the Edit page "Tools" section

- "Add Tool from Catalog" option has been added that allows a user to open the tool catalog. Typing while the catalog is open (chat page only) will filter the options present.
- "Add Tool from URL" option opens a modal that allows users to paste a tool url to add a tool not displayed in the tool catalog. There is also a link to open the tool site in a browser window, and an error will display if an invalid url is provided

**Comment by sangee2004** [comment]
Tested with build `f8cb3bd9`

All the `Add Tool` changes mentioned in the issue is available. Issues seen when testing these features are logged as separate issues.
