### ISSUE TITLE
Issues seen with "Tool Catalog" page.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#221]
electron version - `e8fcaa0fec4765d6`

**Steps to reproduce the problem:**
1. Launch chat page. 
2. Use "Add Tool" option in the chat window with `Tildy` and choose any tool.
Notice that there is no visual indication that the tool has been selected.
**Expected Behavior:**
There should be visual indication that the tool has been selected.
3. Close the "Tool Catalog" page by clicking on "x"
Notice that being able to use "x" to close the "Tool Catalog" page is very elusive. I find it hard to get it to work.
**Expected Behavior:**
Should be able to use "x" to close the "Tool Catalog" page effectively.
4. Once you are in the chat window, try to use "Add tool" again 
Notice that the tool that was added in step 2 is not selected.
**Expected Behavior:**
There should be visual indication that the tool has been selected.

I should also have the ability to unselect the tool that was selected that would result in tool being removed. This is not possible now.

**Comment by thedadams** [comment]
Numbers 2 and 4 are fixed by https://github.com/gptscript-ai/desktop/pull/228

**Comment by sangee2004** [comment]
With builds from `6170a4c97` , i am able to see the tools in `tool catalog` showing as being selected once it gets added. But there is a significant delay in them showing up as being selected after selecting them in `tool catalog` page.

**Comment by cjellick** [comment]
would be much better for the issues to be broken out into separate bugs. For exampl,e the elusivenes of the X has nothing to do with the other bugs.

**Comment by sangee2004** [comment]
All the issues mentioned in the bug are addressed when testing with  the latest build -` a8d8c5c39b3`

We now auto close the tool catalog page as soon as a tool is selected.
