### ISSUE TITLE
Chat page UX enhancements

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#242]
1. The title bar at the top that has the assistant’s name should stay “pinned”, so you don’t lose it when you scroll
2. The title bar should have a toolbox icon that you can click to see a drop down of all the tools that have been added to the assistant and you should be able to remove them from here as well
3. The title bar should have a book icon that you can click to see all the files that have been added as knowledge to the assistant. You should be able to delete them from here and they get removed from the knowledge base
4. The title bar should have a disk icon with hover text that says “Save as custom assistant” that will take you to the editor page with this customized version of the assistant loaded into it. It should have all the tools and knowledge that had been added to the chat.

**Comment by thedadams** [comment]
PR for 1: https://github.com/gptscript-ai/desktop/pull/239

**Comment by thedadams** [comment]
PR for 2: https://github.com/gptscript-ai/desktop/pull/270

**Comment by thedadams** [comment]
PR for 3: https://github.com/gptscript-ai/desktop/pull/279

**Comment by thedadams** [comment]
First PR for 4: https://github.com/gptscript-ai/desktop/pull/288

**Comment by thedadams** [comment]
>The title bar should have a disk icon with hover text that says “Save as custom assistant” that will take you to the editor page with this customized version of the assistant loaded into it. It should have all the tools and knowledge that had been added to the chat.

The requirements here changed. Instead of being taken to the editor page, a modal will appear allowing the user to name the new assistant. After clicking the "Save" button, the tools and files, both assistant and thread, will be copied to the new assistant and this new assistant will be active in the existing thread, replacing the old assistant.

**Comment by thedadams** [comment]
This issue is ready for testing, but, since it is more broad in scope, I would suggest opening new issues for any problems found. That will help with keeping changes separate for testing and fixing.

**Comment by sangee2004** [comment]
Tested with electron build from `91bd0a52`

All the UX enhancements mentioned in the issues are available with this build.
Issues seen when testing these features are reported in separate issues.
