### ISSUE TITLE
Assistant editor page enhancements

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#243]
1. The chat window needs to drop the three dots and `/` functionality. Having “Add Tools” and “Add knowledge” on the chat side is confusing.
2. The user needs a visual indicator that they need to reload the chat when a change is made. Next to the “Finish” button, we should have a “Reload Chat” button. When a user makes a change to the assistant, small text should appear above or below this button that says “Reload chat to apply changes”
3. Change the text of the Finish button to “Back” or “Back to My Assistants”...I’m not sure which will work better

**Comment by sangee2004** [comment]
@njhale  Regarding item2 , I see the "Refresh Chat" have a small dot indicator for this. Wanted to confirm if this is the intended behavior?

![Image](https://github.com/user-attachments/assets/bc0d8182-ebd7-4b21-bbbb-270bc59c7b96)



Also I dont see any changes  item1 is not implemented yet 



![Image](https://github.com/user-attachments/assets/6bb2d804-ad25-42cb-a4ce-e5ca1cabdb6e)

**Comment by sangee2004** [comment]
I see the changes requested in item 1 present in "Edit chat" page.
