### ISSUE TITLE
Knowledge Enhancements

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#246]
On the assistant editor page, we need a knowledge section. This would behave like chatGPT - you add files and then theyre available as a knowledge set whenever you use this assistant. Just get it working locally first. Let’s deal with how it gets saved to the cloud and shared later, but keep it in mind. This is certainly the biggest piece of work as it is more or less new functionality.

Also, with knowledge deeply integrated with the app, we should drop the knowledge tool from the catalog. It is redundant and doesnt work properly. related: https://github.com/gptscript-ai/desktop/issues/235

**Comment by sangee2004** [comment]
Tested with latest build from electron - `97e615c58`

Ability too knowledge files when creating assistants in now supported.
Issues found when testing this feature is logged as separate issues.


I am still able to add knowledge tool from "tool catalog" page when editing assistants.

![Image](https://github.com/user-attachments/assets/1616737d-8272-4085-bf94-746be7057fc2)



![Image](https://github.com/user-attachments/assets/37769546-ddfc-4f83-a315-80e3a40fe780)

Reopening this issue to remove knowledge from "tool catalog".

**Comment by StrongMonkey** [comment]
Hmm, that is still in the search site... @g-linville any idea how to remove that from tool-site?

**Comment by cjellick** [comment]
We are reworking the catalog in this PR: https://github.com/gptscript-ai/desktop/pull/329

That will drop a bunch of entries from the featured catalog page, including knowledge.

The old versions will still be availabe in the tools site. I do not care about that for now. Open a separate issue for that.

I'm going to move this back to testing. You can verify the absence of the knowledge tool from that catalogs when that pr gets meged

**Comment by sangee2004** [comment]
Tested with electron build - `91bd0a52d`

`knowledge` tool is not presented in the featured catalog page anymore. Logged
https://github.com/gptscript-ai/desktop/issues/393 for having to remove `knowledge` from tool site.
