### ISSUE TITLE
Explorer and my assistants page enhancements

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#247]
Exlporer page
1. Next to the title of an assistant there should be a favorite or bookmark icon with hover text that says “Add to My Favorites”. This should cause the assistant to show up in the + dropdown on threads and on the My Assistants page under a new section called Favorites.
2. This entire page should become a modal on the My Assistants page. So, there would be a “Assistant Catalog” button and when you click it, you’d get this modal.

My Assistants page
1. Rename this page in the header navigation from Build to “My Assistants”
2. As discussed above, add an “Assistant Catalog” button and modal
3. Add a new “Favorites” section for catalog assitants that have been favorited. Assistants in this section should not have an “Edit” button. Instead they should have a “Make a Copy” button that opens the editor page with a copy of the assistant and the name of the assistant changed to “Copy of <Assistant Name>”

**Comment by cjellick** [comment]
@StrongMonkey  when we do this, we should revisit the dropdown of assistants you see from the `+` icon on the chat screen. we should surface favorites there.

**Comment by sangee2004** [comment]
Tested with electron build `a8d8c5c39b3d5`

All changes requested in this issue are available.
"Make a Copy” feature has an issue which is tracked in https://github.com/gptscript-ai/desktop/issues/303#issuecomment-2313432526.
We show only 3 favorite assistants tracked in - https://github.com/gptscript-ai/desktop/issues/311
