### ISSUE TITLE
Tools selector enhancments

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#248]
We want to create a better experience around selecting tools.

In the chat screen:
Instead of opening up a modal that takes up the whole screen, we want an experience that builds on the popup you get when you hit the `/` button. So, the tools search will just be down in that area and we'll support auot-searching based on what you type like `/add tool aws`.

On the assistant editor page:
1. Always have an empty textbox at the bottom of the tool list where you could just put in a tool by URL
~2. (phase two, this may need spun out into its own issue) Add a similar tool selector to the empty textbox like described for the chat screen.~

**Comment by njhale** [comment]
We decided we no longer wanted "phase two" of the assistant editor changes out of band.

**Comment by cjellick** [comment]
@ryanhopperlowe im going to move this one to testing. can you open an issue for "phase 2" which is getting the tool selector onto the assistant editor page

**Comment by sangee2004** [comment]
Tested with latest build from `9d46166919`

In chat view:

1. We have the `Add Tool from Catalog` and `Add Tool from URL` as 2 different options


![Image](https://github.com/user-attachments/assets/10dda9c2-cfb6-4dfc-ba05-da17b0ce5184)

2. Clicking on `Add Tool from Catalo`" user is presented with this list of featured tools he is able to add successfully



![Image](https://github.com/user-attachments/assets/9cc7c83d-5659-4865-be36-14bf8ff65ffd)


I am able to search only for the featured tools that are already present in this list. But not able to search for any other tools like "digital ocean"

**Comment by cjellick** [comment]
You should ONLY be able to search for tools that are in that list. That is the intent. We are intentionally trimming the list WAY down

**Comment by sangee2004** [comment]
@cjellick Search in the `tool catalog` page which gets launched from "Edit Assistant" page lets us search for other tools as well. Should this search tool be restricted to only the featured list  as well
?

**Comment by cjellick** [comment]
It is getting updated to match this, yes
