### ISSUE TITLE
Read tool gets called when knowledge tool encounters errors with process knowledge files resulting in string length exceeded errors.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#263]
Electron build -`bf86f18e1c`

**Steps to reproduce the problem:**
1. Chart with `Tildy`
2. Add a pdf file (6.5 MB in my case) using "Add Knowledge"
3. Tried to ask question about information in this pdf file which resulted in knowledge tool not being able to answer and LLM resorted to reading the file using read tool.

This results in following  string length exceeded errors:

<img width="982" alt="Screenshot 2024-08-22 at 1 53 21 PM" src="https://github.com/user-attachments/assets/4625f5c3-9bd8-4434-a40d-6f93dd17d1db">

**Expected Behavior:**
Prevent Read tool from being called for large files which it is not able to handle and results in failure.

**Comment by cjellick** [comment]
need to think about the best way to handle this. the read tool itself should be more ...reluctant?... to blow out the context.

**Comment by cjellick** [comment]
This exact situation shouldn't happen any longer as knowledge has been decoupled from the workspace - https://github.com/gptscript-ai/desktop/pull/360

But @g-linville I still want you to make it so that the read tool doesnt try to read binary files (and potentially just large files or it cuts them off).

**Comment by g-linville** [comment]
This should be good now. The description for sys.read tells the LLM not to use it to read binary files, and sys.read will now return an error back to the LLM if it detects that a file is not plain text.

**Comment by sangee2004** [comment]
Tested with latest build from electron - `81ca1d72a2`

sys.read tool is not  being used for reading  a pdf file .

<img width="881" alt="Screenshot 2024-09-04 at 11 23 04 AM" src="https://github.com/user-attachments/assets/9379de7f-35aa-445c-9240-6320c610db5f">
