### ISSUE TITLE
LLM is not able to respond to chat messages when knowledge tool call fails for an assistant with `workspace` tool and dynamically added knowledge tool.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#264]
Electron build from `bf86f1`

**Steps to reproduce the problem:**
1. Create an assistant with `workspace` tool.
2. Chat with this assistant and add files using "Add Knowledge"
3. Able to chat with the assistant and get information about knowledge files.
4. Ask question about anything other than the knowledge file.
5. Knowledge tool handles the query and fails to retrieve any info which is as expected. But the query is not handled by LLM after this failure and user gets no response for the messages.

<img width="973" alt="Screenshot 2024-08-22 at 3 49 53 PM" src="https://github.com/user-attachments/assets/f056627b-221d-422f-b83e-15a30074e991">

<img width="757" alt="Screenshot 2024-08-22 at 3 49 47 PM" src="https://github.com/user-attachments/assets/0140cc78-4b70-443f-986d-396215b65d94">

**Note** - This behavior is not seen when testing with `Tildy` assistant and adding  files using "Add Knowledge" tool .

**Comment by cjellick** [comment]
@iwilltry42 i would expect this to be addressed by you reworking the knowledge tool into that context-based querier paradigm. assigning to you and using this issue as a place holder for that task

**Comment by sangee2004** [comment]
@iwilltry42 When testing with latest version of desktop with commit id -`d2d9d7ec` and gptscript version - `v0.0.0-dev+fbb8f5d4` , I am not seeing this issue reproduce.

1. Create an assistant with workspace tool.
2. Chat with this assistant and add files using "Add Knowledge"
3. Able to chat with the assistant and get information about knowledge files.
4. Ask question about anything other than the knowledge file.

I see this succeed . I see one of the 2 things happen for this query
1. knowledge tool gets called , returns no match and it resorts to LLM providing the response
<img width="839" alt="Screenshot 2024-08-28 at 9 43 01 PM" src="https://github.com/user-attachments/assets/0d17a80d-ea6c-4203-8486-59698e3afffa">
2. knowledge tool does not get called and LLM responds directly to this query.
<img width="849" alt="Screenshot 2024-08-28 at 9 45 15 PM" src="https://github.com/user-attachments/assets/d9cb08fe-b6d6-41c0-8cf5-098173138a4a">

**Comment by iwilltry42** [comment]
Large changes to how knowledge is integrated: #385

**Comment by sangee2004** [comment]
Blocked on testing with workflow because of https://github.com/gptscript-ai/desktop/issues/425

**Comment by iwilltry42** [comment]
Mitigations and debugging support landed here: https://github.com/gptscript-ai/knowledge/releases/tag/v0.4.13
Waiting for https://github.com/gptscript-ai/desktop/pull/450 to be merged

**Comment by sangee2004** [comment]
Blocked on testing this workflow - https://github.com/gptscript-ai/desktop/issues/425

**Comment by sangee2004** [comment]
Tested with `a66cd29ecd` 
This issue is not seen anymore.
