### ISSUE TITLE
Chat messages overlap with vertical scroll bar in chat view

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#271]
Electron build - `4884a2ba1901c8`

**Steps to reproduce the problem:**
1. Start a chat and have few conversations
2. Use scroll bar to go up

Notice chat messages overlap with vertical scroll bar in chat view.

https://github.com/user-attachments/assets/9eba972e-654b-454b-86c1-e668a3340570

**Comment by thedadams** [comment]
PR: https://github.com/gptscript-ai/desktop/pull/273

**Comment by sangee2004** [comment]
Tested electron build from -  `b4977d084ee`

This issue is not seen anymore.
