### ISSUE TITLE
UI Issues with "Assistant tools" and 'Knowledge" options in thread view.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#287]
Electron build from `d3033b74`

1. Can the color of the highlighted tool/knowledege from "Assistant tools" and 'Thread Knowledge"  be  altered to a different color? It is Red color because of having the remove action associated with selecting the item?

<img width="602" alt="Screenshot 2024-08-26 at 12 23 19 PM" src="https://github.com/user-attachments/assets/ee169ce4-e021-4ee8-b4b8-344bcc8d48ea">

<img width="466" alt="Screenshot 2024-08-26 at 12 07 26 PM" src="https://github.com/user-attachments/assets/05f671da-b390-4174-a138-ddd500a73f4f">

2. Once we remove an entry from  "Assistant tools" /"Thread Knowledge" option , after the removal of tool/knowledge , the "Assistant tools" and 'Thread Knowledge" option lists continue to be presented.
The only way to close this option is to click on the "Assistant tools" /"Thread Knowledge" icon or any where else.

Should we auto close the option lists once an entry is selected for removal and removal is complete?

<img width="967" alt="Screenshot 2024-08-26 at 12 08 10 PM" src="https://github.com/user-attachments/assets/c246dfaa-7247-426e-ad8d-ae965e105096">
<img width="988" alt="Screenshot 2024-08-26 at 12 03 57 PM" src="https://github.com/user-attachments/assets/cac16295-623a-44c5-b0da-c5f5a6a2e855">

3. When there are no `Thread's Tool` or knowledge , Can the "No Tool"/"No Knowldge" be presented in a different font or color to make is obvious that it is not a tool name. Also when we hover over these option , they are presentable as actionable which should not be the case.

https://github.com/user-attachments/assets/b8f4d82d-f4e8-4599-b083-db8e87f6a53a

**Comment by thedadams** [comment]
1 and 2 were explicitly designed and implemented this way.

I will address 3.

**Comment by thedadams** [comment]
PR for 3: https://github.com/gptscript-ai/desktop/pull/292

**Comment by sangee2004** [comment]
Tested with latest build from `74f3564`

Issue relating to #3 in bug is addressed now.

![Image](https://github.com/user-attachments/assets/db2ff52a-e3e1-411f-8779-83158197ce93)
![Image](https://github.com/user-attachments/assets/4de4065c-0b08-4bee-afe3-657ba3051a8a)
