### ISSUE TITLE
Tools from previous thread is shown as tools being available for the newly launched thread

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#289]
**Steps to reproduce the problem:**
1. Start a chat with Tildy , add couple of tools. Have some conversation.In my case I added `outlook mail` and `Slack` tools.
2. Start a new chat with Tildy.
3. Look for tool list by clicking the tools icon for the new thread

Notice the 2 tools from step1 are presented in the Thread's tool list.
<img width="1269" alt="Screenshot 2024-08-26 at 2 25 26 PM" src="https://github.com/user-attachments/assets/b88cde79-3476-4b13-984b-9c3b0c60a1db">

4. Click on "Add tool". Notice that the tool catalog shows the 2 tools from step2 as being enabled for this thread.
<img width="1246" alt="Screenshot 2024-08-26 at 2 25 37 PM" src="https://github.com/user-attachments/assets/deabdadf-cb2c-4c6e-aa3b-04baa4536560">

**Expected Behavior:**
New thread should not show any thread tools.

**Note** - Leaving the thread and re visiting it results in this behavior being created and we see no thread tools in "Assistant Thread" option or in "Tool Catalog"

**Comment by thedadams** [comment]
PR: https://github.com/gptscript-ai/desktop/pull/293
