### ISSUE TITLE
Names of the tools are incorrect when adding tools using "Add tool" option in chat threads.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#290]
Electron build from - `d3033b74d`

**Steps to reproduce the problem:**
1. Start a conversation with `Tildy`
2. Add any tool, using "Add tool" option.
Notice that the tool name is not presented correctly. This is similar to issue fixed in https://github.com/gptscript-ai/desktop/issues/144

This what we see after adding `Slack` and `Outlook Mail` tool using "Add Tool" option.

<img width="925" alt="Screenshot 2024-08-26 at 3 21 36 PM" src="https://github.com/user-attachments/assets/82e2ab75-e053-4f27-a2b2-4c45d0761197">

**Comment by cjellick** [comment]
We've fixed this in several places, but not all

**Comment by sangee2004** [comment]
Tested with electron build -`8809ed1`

Tool name appears as expected with tool tip having the tool url when adding/removing tools to a thread.
![Image](https://github.com/user-attachments/assets/04c98934-97a7-4ce2-ae48-a97609c3c1b8)
![Image](https://github.com/user-attachments/assets/93347a88-dde0-40d0-ad8b-51dea38822a7)
