### ISSUE TITLE
Tool name's get replaced by the tool url in tool list for threads when traversing the  threads list.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#291]
Electron build from commit id `d3033b7`

**Steps to reproduce the problem:**

**Pre Req** - Create few threads and have some tools added to them using "Add Tool" option. 
1. Go to any thread and look at the tools list. 
 You will sometimes notice that the Tool name's get replaced by the tool url in tool list for thread.

If you keep switching between threads  and  clicking the tool icon to list the thread's tool , you will notice this issue start happening in threads which showed the tool names correctly previously. 

<img width="465" alt="Screenshot 2024-08-26 at 3 51 53 PM" src="https://github.com/user-attachments/assets/e20f9e0c-51ee-4d84-9e0a-6b2be7e588cd">

<img width="402" alt="Screenshot 2024-08-26 at 3 51 24 PM" src="https://github.com/user-attachments/assets/31a56bb6-1123-4917-be74-929bc52c5449">

<img width="397" alt="Screenshot 2024-08-26 at 3 51 07 PM" src="https://github.com/user-attachments/assets/be117d8e-e68d-42c6-bbe4-e327cb27cf5d">

**Comment by thedadams** [comment]
This is expected. If we can't get the name, then this is the only thing we can display.

**Comment by sangee2004** [comment]
@thedadams Why would we not be able to get the tool name sometimes?
I see the tool name being displayed most of the time  and not other times (url seen) for the same thread.

**Comment by thedadams** [comment]
I think I found the problem. PR: https://github.com/gptscript-ai/desktop/pull/301

**Comment by thedadams** [comment]
This PR has been merged. Hopefully this fixes the issue. It fixed it when I saw it locally.

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with build - `8bc816e83e`
