### ISSUE TITLE
Can chat menus be left aligned with their icons?

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#299]
![Screenshot 2024-08-27 at 9 50 49 AM](https://github.com/user-attachments/assets/800c68b2-0af4-4f68-83cd-cbb50562e3c2)

They now appear to be centered aligned. Id like to seen them left aligned.

**Comment by thedadams** [comment]
PR: https://github.com/gptscript-ai/desktop/pull/343

**Comment by sangee2004** [comment]
Tested with build from - `d2d9d7ece9`

option list is now left alligned with their icons


![Image](https://github.com/user-attachments/assets/21e49966-8b44-4797-a095-964c82f7bf64)
![Image](https://github.com/user-attachments/assets/df4e4ee3-2829-4bf1-a6c8-5fe5f57414cd)


![Image](https://github.com/user-attachments/assets/cbd0459b-9697-45ae-b118-e9e2046c95e4)
