### ISSUE TITLE
"Save Assistant" thread fails to save assistants.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#303]
Electron build - `74f35645d3e`

**Steps to reproduce the problem:**
1. Create an assistant and add any tool.
2. Chat with this assistant.
3. Use "Save Assistant" option.
Nothing happens.

I see the following error in logs 
```
2024-08-27T18:22:03.299Z [server] [INFO] Error loading tools: failed to load program: failed resolving dynamic-instructions from ./inline: can not load tools path=. name=dynamic-instructions
```

In this case I see the changes getting saved to the assistant but after saving the assistant `dynamic-instructions` tool is lost in the assistant.

Starting an other chat with this assistant fails with following error:

<img width="607" alt="Screenshot 2024-08-27 at 1 06 47 PM" src="https://github.com/user-attachments/assets/275d0269-6868-4f55-aa1f-a4cc9ea9217b">

**Comment by sangee2004** [comment]
Another scenario where we see the same problem:
1.  Mark an assistant as favorite
2. Go to `Favorites` tab in "My Assistants" page and use "Make a Copy" option to create a new assistant.
3. Chatting with this assistant also results in the same "Failed to load program" error relating to `dynamic-instructions` tool.

**Comment by thedadams** [comment]
PR: https://github.com/gptscript-ai/desktop/issues/303

**Comment by sangee2004** [comment]
The workflows mentioned in the issue w.r.to "Save Assistants" and ""Make a Copy" work as expected when testing with electron build - `d4d5806a407`
