### ISSUE TITLE
Change how `dynamic-instruction` tool is presented in Assistant tool list view .

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#304]
Electron build - `74f35645d3e`

**Steps to reproduce the problem:**

1. Create an assistant and add any tool.
2. Chat with this assistant.
3. Use `tools` icon to list all assistant tools

`dynamic-instruction` tool needs to show up as `Dynamic Instructions`
![Screenshot 2024-08-27 at 11 10 46 AM](https://github.com/user-attachments/assets/fea14435-d99c-424a-a9a5-14c5d0447367)

**Comment by thedadams** [comment]
PR: https://github.com/gptscript-ai/desktop/pull/306

**Comment by sangee2004** [comment]
This issue is addressed when testing with build - `8bc816e`
