### ISSUE TITLE
Chat button on assistant catalog does not work

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#309]
Clicking the chat button on any assistant from the "Assistant catalgo" and no chat opens up
Get this error:
```
2024-08-27T21:08:26.173Z [client] [ERROR] Uncaught TypeError: handleCreateThread is not a function
```

Video repro here:
https://www.loom.com/share/a6b6e38b1e9b4ee69d03f2cda5c1c1ca

**Comment by sangee2004** [comment]
Tested with electron build - `2fa0a180691b6de6`

This issue is not seen anymore.
Able to launch a chat thread when using `chat` option for assistants from assistant catalog list.
