### ISSUE TITLE
Remove and re-arrange tools and assitants

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#312]
- Remove all CLI based integrations
- Remove trello, it's terrible
- ~~Hide sys tools behind an advanced tab or something and make their names more user friendly. this needs more discusion.~~

Our featured assistants on the catalog page mainly leverage the cli tools. Delete those too

**Comment by cjellick** [comment]
@ryanhopperlowe should this be in doing or testing?

**Comment by ryanhopperlowe** [comment]
Doing. Moving now

**Comment by sangee2004** [comment]
Following are the list of tools shown in `Tool catalog` page  ( when launched using "Find Tools" option in `Edit Assistant view`  ) and in the tool list shown when using  "Add Tool from Catalog" in chat view.
 


![Image](https://github.com/user-attachments/assets/97e8f6ad-69af-4363-b9fa-45e7754292a8)


@cjellick @ryanhopperlowe Wanted to confirm in this is the final list before I close this issue.

**Comment by cjellick** [comment]
Yeah, this is fine for now
