### ISSUE TITLE
Knowledge - Not able to get information from knowledge file when specifying the name of document to use.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#320]
Electron build from commit id - `a8d8c5c39b3`

**Steps to reproduce the problem**
1. Start a chat with Tildy
2. Add the following  knowledge file using "Add Knowledge" - [MyFeb12.pdf](https://github.com/user-attachments/files/16773407/MyFeb12.pdf)
3. Ask this question - " What can I eat in empty stomach" 
4. Knowledge tool will not get used for this and we get the response from LLM directly.
5. Ask to use the file - "Use MyFeb12 pdf file for this"
6. This results in call being made to Knowledge tool , but the response presented are not from the document even though LLM claims it is from the this document.
<img width="899" alt="Screenshot 2024-08-27 at 5 30 15 PM" src="https://github.com/user-attachments/assets/ac589546-5d7f-46da-8b85-87968adbb626">
[MyFeb12.pdf](https://github.com/user-attachments/files/16773407/MyFeb12.pdf)

<img width="916" alt="Screenshot 2024-08-27 at 5 29 55 PM" src="https://github.com/user-attachments/assets/21298ce0-d6e6-4a52-884a-76f792bd75b8">

**Comment by iwilltry42** [comment]
The LLM decided to use the filename as a keyword parameter.. which is kind of bad, as supposedly the content doesn't contain the filename :confounded: 
As we now have true hybrid search, I'm going to remove that tool.gpt parameter altogether :+1:

**Comment by iwilltry42** [comment]
Large changes to how knowledge is integrated: #385 
-> this removed the param.

Anyway, asking to specifically check a file by name is not expected to do anything right now - it won't make the results better.

**Comment by sangee2004** [comment]
Tested with build - `a66cd29e`
I donot see `know_retrieve_keyword`s parameter being used for` knowledgeRetrieval` tool call.

I am able to get information from knowledge file without having to specify the knowledge file name.

Even if I specify the name, i dont see it getting used by the ` knowledgeRetrieval` tool which is the expected behavior now.

<img width="886" alt="Screenshot 2024-09-09 at 11 40 20 AM" src="https://github.com/user-attachments/assets/4977c654-c0cd-40d1-b607-55a426c4bd37">

<img width="817" alt="Screenshot 2024-09-09 at 11 40 05 AM" src="https://github.com/user-attachments/assets/8c7324e9-33c0-4aeb-8962-c7407e1429ae">
