### ISSUE TITLE
Tildy name flashes on startup

### ISSUE THREAD

**Issue by thedadams** [gptscript-ai/desktop#331]
When starting the app with a thread using a custom assistant, the name of the assistant will briefly flash as "Tildy" and then switch to the correct name.

The "Tildy" name should not flash and the correct name should be used.

**Comment by thedadams** [comment]
PR: https://github.com/gptscript-ai/desktop/pull/337

**Comment by thedadams** [comment]
To reproduce this issue:
- Ensure your top thread is with a custom tool, not Tildy
- Press `Cmd-r` to refresh the page
- You should see Tildy flash at the top of the screen before the name of the assistant shows up

With the proposed changes, that should not happen any longer.

**Comment by sangee2004** [comment]
Tested with electron build `97e615c58`

This issue is not seen anymore.
