### ISSUE TITLE
Do not provide "Save Assistant" option when there are no thread tools.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#332]
Electron build - `d4d5806a407c52`

**Steps to reproduce the problem:**
1. Create an assistant with 1 tool.
2. Start a chat with this assistant.
3. We are provided with "Save Assistant" option which  when used actually saves the assistant.
<img width="921" alt="Screenshot 2024-08-28 at 9 23 18 AM" src="https://github.com/user-attachments/assets/82bf8cd5-fb68-4094-a692-c940fab7849d">

Since there are no tools added to the assistant at this time , we dont have to present this option to the user.

**Comment by cjellick** [comment]
When we have Save As, we need to holistically review all this behavior and make sure it cohesively makes sense.

**Comment by sangee2004** [comment]
This issue is addressed when testing with electron build - `fbd02fab`
