### ISSUE TITLE
Have to click interrupt(cancel) button multiple times to interrupt a message response. 

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#333]
Electron build - `d4d5806a407c52`

**Steps to reproduce the problem**
1. Have an assistant created with outlook mail tool.
2. Chat with this assistant and ask it return emails (make sure that the query will return few entries )
3. When the email contents starts streaming , click on the message interrupt button - <img width="107" alt="Screenshot 2024-08-28 at 10 50 45 AM" src="https://github.com/user-attachments/assets/4c966e29-e956-413e-ab3f-a50b73ec493e">

4. Notice that that this button remains in the same state - <img width="107" alt="Screenshot 2024-08-28 at 10 50 45 AM" src="https://github.com/user-attachments/assets/4c966e29-e956-413e-ab3f-a50b73ec493e">

5. Had to click it the second time for it show the active state - <img width="71" alt="Screenshot 2024-08-28 at 10 51 44 AM" src="https://github.com/user-attachments/assets/be74d3cd-d1cd-471a-bacd-2bfa98287801">

After this , I will see 2 message response (same response twice) being presented in the chat thread

<img width="1031" alt="Screenshot 2024-08-28 at 9 59 01 AM" src="https://github.com/user-attachments/assets/3f6d2395-3e59-470f-aa66-6395d6767c8d">

**Comment by sangee2004** [comment]
This is another instance were I had to click many times before I can actually to get to cancel the response and each cancel attempt results in some response printed in the chat window:

https://github.com/user-attachments/assets/7809fda5-67ce-46a4-8153-be507abc223d

**Comment by thedadams** [comment]
Hoping that this has been fixed.

**Comment by sangee2004** [comment]
Tested with build from `9d4616691`

I am able to see the message response stops streaming as soon as I hit the interrupt/cancel button.
