### ISSUE TITLE
Knowledge - Assistant - Delete button  in File listing needs to be changed to make it more obvious that it is a delete button and user needs to be promoted for confirmation.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#335]
Electron build from - `37b7672110`

**Steps to reproduce the problem:**
1. Create an assistant.
2. Use "+ Files" option and add multiple files ( I added 7 files)

Once ingestion is done , list files
<img width="760" alt="Screenshot 2024-08-28 at 11 37 40 AM" src="https://github.com/user-attachments/assets/46634f7f-bd8d-4dca-ac27-791b533cfe60">

Delete button  in File listing needs to be changed to make it more obvious that it is a delete button .
User needs to be promoted for confirmation . Currently files get deleted with out any confirmation.

**Comment by StrongMonkey** [comment]
This is related to dark mode. Will fix

**Comment by StrongMonkey** [comment]
We are likely not going to add confirmation for now, just align with openai. I don't think it needs confirmation though.

**Comment by cjellick** [comment]
agree. dont worry about confirmation now.

**Comment by StrongMonkey** [comment]
The original issue is fixed because we switched to a different ux. We will not be adding delete confirmation for the time being.

**Comment by sangee2004** [comment]
Tested with electron build - `54ecc2c3`

Delete button is good now.

![Image](https://github.com/user-attachments/assets/194a2199-41ba-4bc8-b0e8-4a9aff1c9b8f)
