### ISSUE TITLE
Knowledge- Assistant - Had to ask for knowledge to be used for query and Citations are also not presented when "fileRetrieval" tool is called.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#336]
Electron build from - `37b7672110`

**Steps to reproduce the problem:**
1. Create an assistant.
2. Use "+ Files" option and add multiple files 
3. Chat with the assistant about 1 of the file that was uploaded [2023q4-alphabet-earnings-release.pdf](https://github.com/user-attachments/files/16787653/2023q4-alphabet-earnings-release.pdf)
4. Asked - `What is alphabets earnings ?` - There was no tool call made to "fileRetrieval" 
5. Asked - ` What is alphabets earnings ? Use knowledge` - There was no tool call made to "fileRetrieval" but response did not have any citations
6. Asked - `What is alphabets earnings ? Use knowledge. Provide citations` - I was able to get the response from knowledge file with citations.

**Expected Behavior:**
I should be able to get the responses from knowledge file with citations without having to ask it ot "Use knowledge. Provide citations"

**Note** - I dont see any Knowledge context tool being used in the stack trace view.

**Comment by cjellick** [comment]
I'm expecting the prompting part to be addressed as part of @iwilltry42's changes on how the equery tool is integration

Citations is a separate issue and I've said this in other places but will reiterate here: we SHOULD NOT give citations by default. We cannot assume that all usecases of knowledge want the citation surfaced. If I were creating a customer facing chatbot where the source documents are not available to the end user, giving a citation would be the wrong behavior.

**Comment by sangee2004** [comment]
I am documenting another use case for me to test as well when this issue gets addressed:

1. Create an assistant with knowledge file ( 1 file - reunion-under-the-star story)
2. Chat with this assistant and add knowledge file (travel plan pdf) to thread using "Add knowledge" option.
3. Chat with assistant ask - "What are my travel plans for day 8"
4. I get a response as expected from `knowledgeRetreivalTool`
5. Ask a question about assistant's knowledge file -  "What is the story of reunion under the star about ?"
6.  I get a response from LLM  without any tool calls.
7.  Ask - What is the story of reunion under the star about ? Use Knowledge"
8. This results in tool call being made to  `knowledgeRetreivalTool` which does not have any information regarding this query
9. Ask - What is the story of reunion under the star about ? Use File-Retrieval"

Now I am able to get information from the assistant knowledge files.

![Image](https://github.com/user-attachments/assets/391c24df-76f6-463e-abc1-8330c1cb0a00)


**Expected Behavior:**

I  should be able to get information from the assistant knowledge file with out having to ask it specifically to use   File-Retrieval tool.

**Comment by iwilltry42** [comment]
Large changes to how knowledge is integrated: #385

**Comment by sangee2004** [comment]
Testing with latest build -  `a66cd29e`

I am still able to reproduce the issue mentioned in the bug
1. Create an assistant with following files:
[Reunion-Under-The-Stars.pdf](https://github.com/user-attachments/files/16935398/Reunion-Under-The-Stars.pdf)
[Holiday List_2024.pdf](https://github.com/user-attachments/files/16935400/Holiday.List_2024.pdf)
[essay.pdf](https://github.com/user-attachments/files/16935396/essay.pdf)
[dictionary.pdf](https://github.com/user-attachments/files/16935397/dictionary.pdf)
[Insurance_Handbook_20103.pdf](https://github.com/user-attachments/files/16935399/Insurance_Handbook_20103.pdf)
[2023q4-alphabet-earnings-release.pdf](https://github.com/user-attachments/files/16935401/2023q4-alphabet-earnings-release.pdf)

2. Chat with this assistant and ask `What is alphabets earnings ?` . I get the following response
```
Alphabet Inc., the parent company of Google, reports its earnings on a quarterly basis. The earnings reports typically include key financial metrics such as revenue, net income, earnings per share (EPS), and other relevant financial data.

3. But when asked to use knowledge tool , i get the desired response.

To provide you with the most recent and accurate earnings information for Alphabet Inc., I can look up the latest earnings report. Would you like me to do that?
```
![Image](https://github.com/user-attachments/assets/c34db52a-f93a-4961-aea2-24b9c8a321b7)


Note i am not able to attach the full stack trace because of contents from `Knowledge Retrieval Context` is very large

For `What is alphabets earnings ?`
![Image](https://github.com/user-attachments/assets/3a518ff0-def7-40e2-9578-c3b0b8677d50)

For `What is alphabets earnings ? Use knowledge`
![Image](https://github.com/user-attachments/assets/84f44f55-d3e5-488f-b99c-d44a4638c585)

**Comment by sangee2004** [comment]
Tested with electron build -`8809ed131d3`

This issues mentioned in the bug are not reproducible anymore.
