### ISSUE TITLE
Knowledge - Assistant - Show the list of knowledge files associated with an assistant in chat view

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#338]
Electron build from - `37b7672110`

**Steps to reproduce the problem:**
1. Create an assistant.
2. Use "+ Files" option and add few files
3. Chat with this assistant.

Notice that  clicking on `Knowledge` icon shows no knowledge files associated with the assistant.

**Expected Behavior:**
We should be able to provide information about all the files associated with the assistant in the chat view.

**Comment by cjellick** [comment]
This is not necessarily the correct or desired behavior. We may not want to go down to that level of granularity. We may just want to show "This assistant has a custom knowledge set." The source documents may or may not be relevant to the end user.

**Comment by sangee2004** [comment]
This issue is addressed when testing with electron build -` fbd02fab`
