### ISSUE TITLE
"My Assistants" page stuck in loading state forever

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#341]
Electron build - `4a596e37`

**Steps to reproduce the problem:**
1. Lauch app
2. Go to "My Assistants" page. 

Notice that "My Assistants" page stuck in loading state forever.

"Cmd -r" gets us out of this state.

**Comment by thedadams** [comment]
PR: https://github.com/gptscript-ai/desktop/pull/342

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with `97e615c5`
