### ISSUE TITLE
Outlook Email tool - Not able to get the full content of the email body

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#361]
Electron build - 2fa0a18069

**Steps to reproduce the problem:**
1. Start a chat with Tildy.
2. Add Outlook Mail tool.
3. Ask To list some mail.

Notice that only `Body preview` is provided which is truncated version of the email body.

<img width="872" alt="Screenshot 2024-08-29 at 12 50 55 PM" src="https://github.com/user-attachments/assets/11e2a3d2-344e-4e9f-a0da-72342f0d9c2a">

There is also no link that would take us to the actual email made available in the response.

Expected Behavior:
There should be a way to read the full email content.

**Comment by g-linville** [comment]
There is a `getMessageDetails` tool that will be able to get the full body.

**Comment by sangee2004** [comment]
When testing with the latest version of the tool , we see the "Read Email" link that opens up email outlook client for the email.


![Image](https://github.com/user-attachments/assets/7fd7f691-a026-49aa-8679-830ba4c7d79d)


@g-linville Do we want to continue to also show the Body Preview which we used to show before?

**Comment by g-linville** [comment]
@sangee2004 I'm a little surprised that it didn't display the body preview. I'll tweak its prompt in order to encourage it to do so.

**Comment by g-linville** [comment]
@sangee2004 I adjusted the prompt that we give to the LLM with the mail tools, so it should start printing the body preview again.

**Comment by sangee2004** [comment]
@g-linville When testing with the latest version , i am seeing the link to email missing and only body preview is present.



![Image](https://github.com/user-attachments/assets/e38ac130-b4a6-4953-a649-7d9a8ecf1e10)

**Comment by g-linville** [comment]
@sangee2004 the LLM should now include the email links without you having to ask it to do so.

**Comment by sangee2004** [comment]
Tested with the latest version of outlook email tool.
I see the Body preview and email link now. But email list is not  formatted correctly.


<img width="812" alt="Screenshot 2024-09-05 at 12 11 10 PM" src="https://github.com/user-attachments/assets/0de102e2-2fdd-4413-87a8-cd906f3d951b">


@g-linville Reopening to get the formatting issues addressed.

**Comment by g-linville** [comment]
The formatting should look good now.

**Comment by sangee2004** [comment]
Formatting of the emails look good now.
