### ISSUE TITLE
Outlook Mail Tool - Not able to search emails that were sent from a person by name or email id.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#366]
Electron build - https://github.com/gptscript-ai/desktop/commit/2fa0a180691b6de6c7a678015415f9ba6595ef91

**Steps to reproduce the problem:**

1. Start a chat with Tildy.
2. Add Outlook Mail tool.
3. Ask to list all emails from a person by name or email id.

Notice that there are multiple attempts made and no emails get returned. In my case email i was expecting was from Aug 15th.

This seems to be very similar to https://github.com/gptscript-ai/desktop/issues/36 where the searchMessages call always fails and a call to listMessage with folderid is done with no other criteria which results in only emails from last 7 days being returned.

<img width="728" alt="Screenshot 2024-08-29 at 4 57 27 PM" src="https://github.com/user-attachments/assets/dea43c08-207c-4677-b0a0-70f83eaa15d5">

<img width="825" alt="Screenshot 2024-08-29 at 4 59 02 PM" src="https://github.com/user-attachments/assets/99bdbe04-054a-4068-8178-9ee6f929c69f">

When I use the email id , i see the same problem . But in this case the calls keeps failing and get retried in an infinite loop and results in "500 Internal Server Error"

<img width="991" alt="Screenshot 2024-08-29 at 5 01 17 PM" src="https://github.com/user-attachments/assets/7a1a4d59-5445-4ac5-83b9-4aaa793cd0ac">

<img width="948" alt="Screenshot 2024-08-29 at 3 24 48 PM" src="https://github.com/user-attachments/assets/43f2dc9a-11b7-4e19-b7be-c5a2e2813c7f">

<img width="803" alt="Screenshot 2024-08-29 at 3 26 57 PM" src="https://github.com/user-attachments/assets/8ed2674d-1a3b-43c5-accc-8134a8dc4c07">

**Note** - In some cases , i see the search fail after multiple attempt and resorts to list Folder call and is able to present the response if there were emails that matched the criteria in the last 7 days.

 
<img width="862" alt="Screenshot 2024-08-29 at 3 31 46 PM" src="https://github.com/user-attachments/assets/daa7a3da-0608-4a79-9f9a-8fa47e928720">

**Comment by g-linville** [comment]
Added the ability to do this with my latest PR.

**Comment by sangee2004** [comment]
Able to search successfully for emails using email ids and person name .
