### ISSUE TITLE
Fix errors being thrown as strings within NextJs server actions

### ISSUE THREAD

**Issue by ryanhopperlowe** [gptscript-ai/desktop#368]

**Comment by thedadams** [comment]
PR: https://github.com/gptscript-ai/desktop/pull/394

**Comment by thedadams** [comment]
The easiest way to test this is from the Chat view.

Add a tool from a URL. In the text box, enter something that is not a URL, like hello. If you see a red error appear on the page, then this is working. If no error appears, then it is broken.

**Comment by sangee2004** [comment]
Tested with electron build - `54ecc2c334`

Following error is presented to the user when bad url is used when adding tools using `Add Tool from URL" option.

![Image](https://github.com/user-attachments/assets/6283cfa6-614b-41ec-856d-45caf06ebff3)
