### ISSUE TITLE
Revisiting the thread  that had used "Save assistant as" option resets to older assistant.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#391]
Electron build -`fbd02fab3`

**Steps to reproduce the problem:**
1. Create an assistant with outlook tool - "sangeetest1outlook"
2. Chat with this thread.
3. Add slack tool using "Add Tool from Catalog" page
4. Have conversation relating to  slack tool.
5. Use "Save assistant as" option to create an new assistant -  "ooo"
Notice that the thread name changes to new assistant and "Assistant Tools" list shows outlook and slack tool as expected.
6. Have conversation relating to  slack tool. Succeeds as expected.
7. Leave this thread ( by going to other thread)
8. Revisit this thread ( that was created in step2)
9. Notice that the thread now shows the assistant name as "sangeetest1outlook" and does not have slack tool anymore.

**Expected Behavior:**
Thread should be associated with the new assistant for the thread when it  is revisited.

**Note** - This issue fixes itself when manual refresh "cmd r" with the thread selected. It get the updated assistant name "ooo" .

https://github.com/user-attachments/assets/12b6572b-40e6-46a0-ba69-a74c543a87a4

**Comment by cjellick** [comment]
> 9. Notice that the thread now shows the assistant name as "ooo" and does not have slack tool anymore.

I think you mean the name shows as "sangeetest1outlook", which is the original name

**Comment by sangee2004** [comment]
I will update the description accordingly.

**Comment by thedadams** [comment]
PR: https://github.com/gptscript-ai/desktop/pull/464

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with `a66cd29`
