### ISSUE TITLE
Not able work with knowledge files adding using "Add knowledge" after using "Save Assistant As" option.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#395]
Electron build -`91bd0a52d`

**Steps to reproduce the problem:**
1. Start a chat with `Tildy`
2. Use “Add knowledge” to add knowledge file.
3. Use “Save Assistant As..”  option to create a new assistant.
4. Wait for the thread to reload with the new assistant.
5. Ask for any question relating to the knowledge file.

We are not able to get knowledge tool to be used for this query.

https://github.com/user-attachments/assets/57b4984a-6d92-4b93-b8e3-7e0e59914b8b

**Comment by sangee2004** [comment]
I am able to work with the knowledge file if I used ""Use the file retrieval tool to get a list of the Acorn Labs holidays" instead of using "Get the list of holidays. Use file retrieval" as my message.

**Comment by thedadams** [comment]
@cjellick Seema like a duplicate of https://github.com/gptscript-ai/desktop/issues/336

**Comment by thedadams** [comment]
I am seeing that this is addressed with the latest changes made to the knowledge tool.

**Comment by sangee2004** [comment]
Tested with latest build from `a66cd29ec`

This issue is not seen anymore.
