### ISSUE TITLE
Chat reloads and loses long messages

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#403]
I dont have exact steps to repro yet, but I hit this multiple times: it seems if the UI is generating a long response, it will sometimes just reload and lose that long response as well as the question i asked that kicked it off. This happens pretty late in the response generation, so it's very frustating because you lose everything it was writing.

**Comment by sangee2004** [comment]
I have not been able to reproduce this issue when testing with latest builds of electron app.

We have the following 2 related issues for tracking the behavior seen with long message truncation and sometimes seeing the thread possibly restart and having 2 welcome messages

https://github.com/gptscript-ai/desktop/issues/432
https://github.com/gptscript-ai/desktop/issues/108
