### ISSUE TITLE
Big delay with no feedback when a message is first kicked off

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#404]
@thedadams brought this up in standup and i am seeing it as well.

It takes several seconds before we even give any feedback to a user after they send a message.

We think this is because the context now takes longer to generate because of the call to knowledge.

**Comment by tylerslaton** [comment]
https://github.com/gptscript-ai/desktop/pull/428

**Comment by sangee2004** [comment]
Tested with electron build -  `9d3d776c3`

We are presented with "Waiting for model response.." message as soon as we send any chat message now.

But this fix seems to have introduced the following 2 issues which were not seen before:

https://github.com/gptscript-ai/desktop/issues/437
https://github.com/gptscript-ai/desktop/issues/438
