### ISSUE TITLE
Move Dynamic Instructions to the Advanced Tab

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#408]
Request to move the Dynamic Instructions feature to the Advanced tab for better organization and user experience.

**Comment by sangee2004** [comment]
Tested with build - `29efc7879dad`

`Dynamic instructions` is now moved to the Advanced Tab.

![Image](https://github.com/user-attachments/assets/33e4cde1-90ee-49db-a78d-abe42e7bb086)

![Image](https://github.com/user-attachments/assets/96058612-18b6-40db-9d77-af2d69c2480f)
