### ISSUE TITLE
Tool parameters dont work and dont persist

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#413]
Recorded a loom for it:
https://www.loom.com/share/518a812fafa8477cb226d73489740c2f

but tl;dr the param entries on the "sub tool" modal dont seem to stick around or work properly

**Comment by cjellick** [comment]
@tylerslaton are you working on this? I believe you sent me a video of a fix.

If so, please move this to "Doing"

**Comment by sangee2004** [comment]
Tested with electron build - `e6f2a4aaa`

Tool parameters set on custom tools persists now.
