### ISSUE TITLE
Stop button does not work

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#416]
Stop button really really doesnt work well at all. Most of the time nothing happens when I click it. May or may not be happening specifically around tool calls

**Comment by sangee2004** [comment]
Is this relating to cancelling a chat response ? - https://github.com/gptscript-ai/desktop/issues/333

**Comment by thedadams** [comment]
Hoping that this has been fixed.

**Comment by cjellick** [comment]
yes...but even clicking multiple times does nothing. i can click it a thousand times and the chat does not stop

**Comment by cjellick** [comment]
was testing this out today and it seems like its kind of working now... the first click was stoppping. i had to click again to get the button back to send. but then, the message that was in progress is deleted. we should not delete the in progress message.

**Comment by tylerslaton** [comment]
Yeah I also noticed the button seemed to be working fine, I'm doing a more in-depths dive into it right now to try and figure out how to improve. If you did have a case where the button does not work can you link it here?

As for the in progress message being deleted that sounds like a regression, it didn't do that before so I'll fix that too.

**Comment by tylerslaton** [comment]
https://github.com/gptscript-ai/desktop/pull/495

**Comment by sangee2004** [comment]
Tested with latest build from `57e1a5c98`

I had to click on `stop` twice for the message processing to stop actually.
And I see the response being printed twice in the chat window.
Once i quit the thread and revisit it , I dont see the message and the response that was stopped in the chat view.
This behavior seems very similar to https://github.com/gptscript-ai/desktop/issues/333 which was addressed earlier.

https://github.com/user-attachments/assets/609bb1f1-4648-4a79-bcc7-9890581487d6

**Comment by tylerslaton** [comment]
https://github.com/gptscript-ai/desktop/pull/498

**Comment by sangee2004** [comment]
Tested with build - `809ed131`

Able see messages being stopped when clicking on `stop` button once.

We still have the issue with the chat message and response (interrupted) being lost when the thread is revisted.

This issue is tracked in https://github.com/gptscript-ai/desktop/issues/500
