### ISSUE TITLE
Error message presented to the user gives no useful information when adding a tool with invalid url.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#423]
Electron build -  `81ca1d7`

**Steps to reproduce the problem:**
1. Chat with `Tildy`
2. Use "Add Tool from URL" option and add invalid url like `github.com/trash`.

User is presented with the following error message:

<img width="494" alt="Screenshot 2024-09-04 at 10 29 42 AM" src="https://github.com/user-attachments/assets/1427f54f-57cb-45d1-814e-505a5a027ee3">

**Expected Behavior:**
Error message presented to the user should be more meaningful.

**Comment by sangee2004** [comment]
There is also another case where I see the same error message being presented to the user when uploading of knowledge file failed because of a DNS issue

<img width="903" alt="Screenshot 2024-09-04 at 12 55 17 PM" src="https://github.com/user-attachments/assets/66bd7073-cde7-4525-8e52-8a023d101826">



Errors seen in console:
```
2024-09-04T19:48:05.825Z [server] [ERROR] Error: Command failed: /Users/sangeethahariharan/acorn/desktop/bin/knowledge ingest --prune --dataset nde6ei /Users/sangeethahariharan/Library/Application\ Support/acorn/Acorn/threads/nde6ei/knowledge
2024/09/04 12:47:45 INFO Created dataset id=nde6ei
2024/09/04 12:47:45 INFO Pruned files count=0 basePath="/Users/sangeethahariharan/Library/Application Support/acorn/Acorn/threads/nde6ei/knowledge"
2024/09/04 12:48:05 ERROR Failed to add documents error="couldn't add document '908f16fc-b8f4-4e43-936e-09cd5354ab6d': couldn't create embedding of document: couldn't send request: Post \"https://gateway-api.gptscript.ai/llm/embeddings\": dial tcp: lookup gateway-api.gptscript.ai on 192.168.1.254:53: read udp 192.168.1.76:56756->192.168.1.254:53: i/o timeout"
2024/09/04 12:48:05 failed to add documents: couldn't add document '908f16fc-b8f4-4e43-936e-09cd5354ab6d': couldn't create embedding of document: couldn't send request: Post "https://gateway-api.gptscript.ai/llm/embeddings": dial tcp: lookup gateway-api.gptscript.ai on 192.168.1.254:53: read udp 192.168.1.76:56756->192.168.1.254:53: i/o timeout

    at genericNodeError (node:internal/errors:984:15)
    at wrappedFn (node:internal/errors:538:14)
    at ChildProcess.exithandler (node:child_process:422:12)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:338:12)
    at Pipe.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 1,
  killed: false,
  signal: null,
  cmd: '/Users/sangeethahariharan/acorn/desktop/bin/knowledge ingest --prune --dataset nde6ei /Users/sangeethahariharan/Library/Application\\ Support/acorn/Acorn/threads/nde6ei/knowledge',
  stdout: '',
  stderr: '2024/09/04 12:47:45 INFO Created dataset id=nde6ei\n' +
    '2024/09/04 12:47:45 INFO Pruned files count=0 basePath="/Users/sangeethahariharan/Library/Application Support/acorn/Acorn/threads/nde6ei/knowledge"\n' +
    `2024/09/04 12:48:05 ERROR Failed to add documents error="couldn't add document '908f16fc-b8f4-4e43-936e-09cd5354ab6d': couldn't create embedding of document: couldn't send request: Post \\"https://gateway-api.gptscript.ai/llm/embeddings\\": dial tcp: lookup gateway-api.gptscript.ai on 192.168.1.254:53: read udp 192.168.1.76:56756->192.168.1.254:53: i/o timeout"\n` +
    `2024/09/04 12:48:05 failed to add documents: couldn't add document '908f16fc-b8f4-4e43-936e-09cd5354ab6d': couldn't create embedding of document: couldn't send request: Post "https://gateway-api.gptscript.ai/llm/embeddings": dial tcp: lookup gateway-api.gptscript.ai on 192.168.1.254:53: read udp 192.168.1.76:56756->192.168.1.254:53: i/o timeout\n`,
  digest: '1602320271'
}
```

**Comment by ryanhopperlowe** [comment]
@cjellick - The first issue should be solved already with #483 

@sangee2004 - Do you have steps to reproduce for the second issue? I've tried uploading files, and I'm not able to get that DNS Error

**Comment by sangee2004** [comment]
@ryanhopperlowe The issue with knowledge file upload happens randomly. I dont have reproducible steps to get to this state.

**Comment by cjellick** [comment]
> There is also another case where I see the same error message being presented to the user when uploading of knowledge file failed because of a DNS issue

completely separate bug from "Error message presented to the user gives no useful information when adding a tool with invalid url."

you can open a separate issue from the second one. the original issue should be addressed.

**Comment by sangee2004** [comment]
Logged https://github.com/gptscript-ai/desktop/issues/508 for tracking issue seen with error message not being shown to user when knowledge file addition fails.

**Comment by sangee2004** [comment]
Tested with electron build - `0f259cd7e`

Proper error message is presented to the user.

![Image](https://github.com/user-attachments/assets/21559ba7-bc05-4cdd-8f86-2b4d0c07347a)
