### ISSUE TITLE
Turn off Confirmation by default

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#431]
Let's introduce a setting (using Nick's new setting page) that will globally turn the allow prompting on/off. 

By default, prompting should be disabled and we shoulld just auto-approve everything. You can turn prompting on and get the current Allow/Allow All/Deny behavior

**Comment by sangee2004** [comment]
Tested with electron build - `e6f2a4aaa`

Confirmation is turned off by default now.

I am not presented with any confirmation prompts when working with tools like image generation tools which used to be the case before.
Even activities relating to deletion like mail deleted (using outlook Mail tool) does not prompt for confirmation  before deleting.
