### ISSUE TITLE
Adding of tools fails intermittently with "Tool already added" error

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#433]
Electron build - `0d607f99754`

**Steps to reproduce the problem:**

There is not reproducible steps to hit this issue.
But if you keep trying to add multiple tools to a thread ( i have tried with  notion, slack , outlook mail, calendar), you will see the tool fails to get added and you will see " Tool already added" error in the logs.

In this recording you will see outlook mail and calendar tool fail to get added. I have seen notion and slack tools fail tool. Failure to add a tool happens sometimes even to the first tool added to the thread.

https://github.com/user-attachments/assets/3448c793-bf35-48c5-b412-92f7bb4a5691

Following error seen in logs:

"2024-09-05T00:34:04.056Z [client] [ERROR] Error: Tool already added"

**Comment by sangee2004** [comment]
I have reproducible steps for this issue:

1. Start a new chat with `Tildy`
2. Add any tool - say `slack`
3. Do not have any conversation in this thread
4. Start an other new chat with `Tildy`
5. Add the same tool as in step 2 - `slack` in my case

This will fail to add with `Error: Tool already added` error.

**Comment by cjellick** [comment]
Ah, thats a fun one. I can repro with your steps as well

**Comment by sangee2004** [comment]
Tested with build from `9d3d776c3`

This issue is not seen anymore.
