### ISSUE TITLE
`Calling tool ..` message does not get cleared even after allowing the tool confirmation prompt and response is received

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#437]
Electron build - `9d3d776c3f`

**Steps to reproduce the problem:**
1. Chat with `Tildy`
2. Ask any question that involves the browser tool.
3.  Choose "Allow all" when prompted for tool confirmation

Notice that `Calling tool ..` message continues to be present in the chat view , even after  allowing the tool confirmation prompt and response is received
<img width="888" alt="Screenshot 2024-09-05 at 11 24 33 AM" src="https://github.com/user-attachments/assets/071cc596-a75b-41b9-810f-50a97c8b62ab">
<img width="886" alt="Screenshot 2024-09-05 at 11 25 12 AM" src="https://github.com/user-attachments/assets/0351f68e-f221-412f-b24f-59eaeeb34331">

Same behavior is seen for any tool that has confirmation prompt workflow.

<img width="907" alt="Screenshot 2024-09-05 at 11 30 39 AM" src="https://github.com/user-attachments/assets/b3671089-db31-49d3-b117-b7a6aa921b62">

**Comment by tylerslaton** [comment]
https://github.com/gptscript-ai/desktop/pull/439

**Comment by thedadams** [comment]
It looks like this one was fixed by our reorganization of how the latest agent message was handled. Moving to Testing for verification.

**Comment by sangee2004** [comment]
Tested with `2be2f66601`
We are not prompted for tool confirmation anymore for browser tool calls.

I see this issue fixed when testing with image generation tool.
