### ISSUE TITLE
"Waiting for model response.." message does not get cleared even oauth workflow is completed and response is received.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#438]
Electron build - `9d3d776c3f1`

PreReq - Make sure you do not have outlook mail credentials
**Steps to reproduce the problem:**
1. Chat with `Tildy`
2. Add outlook mail tool.
3. Ask some information about email.
4. Once presented with the oauth workflow,  complete it.

Notice that even after the response it presented to the user , the  "Waiting for model response.." message does not get cleared in the chat view.

<img width="888" alt="Screenshot 2024-09-05 at 11 38 27 AM" src="https://github.com/user-attachments/assets/d4a4d02c-3016-4591-93d4-56c9873f87f6">

**Comment by tylerslaton** [comment]
https://github.com/gptscript-ai/desktop/pull/439

**Comment by cjellick** [comment]
@tylerslaton is this a regression introduced by your change for the delay issue?

**Comment by tylerslaton** [comment]
Yes. I missed adding updating some that needed to be updated alongside some event handlers. There was a PR I put out earlier but was closed since Nick is overhauling all of this as discussed offline.

**Comment by cjellick** [comment]
@sangee2004 i cannot reproduce this now. im going to kick back to you

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with `2be2f666016`
