### ISSUE TITLE
Slack Tool - When asking for recent message sent by a person in channel, i get DM messages.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#447]
Electron build- `f8cb3bd`

**Steps to reproduce the problem:**
1. Chat with `Acorn Engineering` assistant.
2. Ask for the most discussion from me in Engineering channel -  `Get the most recent discussion by <current user> in Engineering channel`

I get the response as a slack message that was a DM to someone and not the message from the Channel

Tool calls done in this case dont use the channel information provided.
```
 Input
"Get the most recent discussion by sangeetha in Engineering channel"

Messages
<tool call> searchUsers -> {"query":"sangeetha"}

<tool call> searchMessages -> {"query":"from:sangeetha","sort":"timestamp","sort_dir":"desc","count":"1"}

The most recent discussion by Sangeetha in the Engineering channel is as follows: > **Sangeetha**: When I mark issues as "High", I am having "help wanted" tag for you to review the priority as we had discussed. Wanted to let you know that I am not marking any issues as "Release Blockers". (9/5/2024, 5:02:30 PM) If you need more details or further assistance, feel free to ask!
```

**Comment by cjellick** [comment]
maybe this can be improved by adding some examples to the query parameter

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with otto
