### ISSUE TITLE
Welcome message not shown in "Edit Assistant" page. 

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#453]
Electron build -`9bf8a`

**Steps to reproduce the problem:**
1. Create an assistant( with or without any tools)
2. Use "Refresh Chat" option in Edit assistant page.
3. Notice that the welcome message is not presented in the chat window.

https://github.com/user-attachments/assets/71610c01-62d4-49d7-aead-69122d851655

**Comment by cjellick** [comment]
appears to be fixed. i cannot reproduce

**Comment by sangee2004** [comment]
This issue is not seen when testing with `2be2f666016`
