### ISSUE TITLE
Knowlege - There are no errors logged in log files when ingestion/retrievals fail.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#457]
Electron build - 9bf8a0660d4ad

Knowlege tool version - v0.4.13

When we encounter knowldge ingestion/retrievals failures like in  - https://github.com/gptscript-ai/desktop/issues/456 and https://github.com/gptscript-ai/desktop/issues/455  , there are no logs about the errors encountered in acorn.log file.

**Expected Behavior:**
 acorn.log should have information and stack traces relating to these errors.

**Comment by StrongMonkey** [comment]
@sangee2004 The ingestion log should be print to acorn.log now.

**Comment by sangee2004** [comment]
Tested with electron build - `18eaca7d`

I am able to see logs relating to file ingestion being written to acorn.logs
```
2024-09-10T22:55:32.795Z [server] [INFO] logs for ingesting dataset q3hvhq:  Ingested 1 files from "/Users/sangeethahariharan/Library/Application Support/acorn/Acorn/threads/q3hvhq/knowledge" into dataset "q3hvhq"
2024/09/10 15:55:17 INFO Created dataset id=q3hvhq
2024/09/10 15:55:17 INFO Pruned files count=0 basePath="/Users/sangeethahariharan/Library/Application Support/acorn/Acorn/threads/q3hvhq/knowledge"
warning: expected name after CMapName in cmap
2024/09/10 15:55:32 INFO Ingested document filename=1000-Ways-to-Make-1000-Dollars.pdf count=834 absolute_path="/Users/sangeethahariharan/Library/Application Support/acorn/Acorn/threads/q3hvhq/knowledge/1000-Ways-to-Make-1000-Dollars.pdf"
```

**Comment by sangee2004** [comment]
Reopening this issue.

I am not seeing any error logs being logged in the log files when ingestion fails.These errors get reported in the UI . But they are not logged in acorn.log files.

**Comment by sangee2004** [comment]
Tested with electron build -` 9354f78ee44`

I am able to see the failures reported during ingestion being logged as expected in acorn log file now. There is a problem with logs from knowledge tool getting truncated which will be tracked in a different issue.
