### ISSUE TITLE
Chatting with an assistant that has knowledge file gets stuck in "Waiting for model response..." page forever and no welcome message is presented.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#459]
Electron build - `9bf8a0660d4`

**Steps to reproduce the problem:**
1. Create an assistant with file - 
[Holiday List_2024.pdf](https://github.com/user-attachments/files/16913122/Holiday.List_2024.pdf)

2. Chat with this assistant

Notice that we are presented with "Waiting for model response..." page forever and no welcome message is presented.

<img width="1263" alt="Screenshot 2024-09-06 at 2 41 06 PM" src="https://github.com/user-attachments/assets/ed5a273b-9285-4f61-9954-a8f30f7b2c10">

3. Send a chat message

Notice that we get 2 responses presented 

<img width="908" alt="Screenshot 2024-09-06 at 2 49 59 PM" src="https://github.com/user-attachments/assets/b0112b4e-56da-4ea6-be96-5751cbfdcaa0">

**Comment by cjellick** [comment]
is this reproducible?

**Comment by sangee2004** [comment]
This issue was reproducible always with the build mentioned in the issue.

I dont see this issue anymore when testing with latest build - `0feebf947c`
