### ISSUE TITLE
Acorn Engineer - Stuck in "Notion Integration requires authentication" state 

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#460]
Electron build -`0feebf947c6` ( Have seen this issue even when testing with older builds)

**Steps to reproduce the problem:**
1. Clear all cache and config
```
rm -rf ~/Library/Application\ Support/acorn
rm -rf ~/Library/Application\ Support/gptscript
rm -rf ~/Library/Caches/gptscript
```
2. Delete for existing credentials
3. Chat with "Acorn Engineer" assistant
After the outh flow for `github.write` , we are stuck in this page forever
<img width="930" alt="Screenshot 2024-09-06 at 5 45 40 PM" src="https://github.com/user-attachments/assets/18021f31-6b0b-404f-b983-43c30308e609">

At this time , notion related credentials are not created anymore even when the status in UI shows as being `Submitted`

```
gptscript credentials
CREDENTIAL                        EXPIRES IN
github.com/gptscript-ai/gateway   83h47m33s
github.write                      never
outlook.mail.manage               1h4m53s
```

**Comment by cjellick** [comment]
Not sure whats going on here, but ive experienced the same thing. credential prompting is totally jacked up and almost always gets stuck

**Comment by cjellick** [comment]
I mainly hit funkiness if my assistant has more than credential prompt. This one induces it consistently for me:

```
Name: SA
Description: Always Be Closing. This assistant will help you research and follow up on leads using Hubspot, Outlook, Slack, and the Internet
Type: Tool
Tools: github.com/gptscript-ai/tools/apis/slack/write, github.com/gptscript-ai/tools/apis/outlook/mail/manage, github.com/gptscript-ai/tools/apis/outlook/calendar/manage, github.com/gptscript-ai/answers-from-the-internet, github.com/gptscript-ai/context/workspace, github.com/cjellick/tools/apis/hubspot/crm/write
Chat: true

You help sales reps with turning leads into closed deals.

Important guidelines and hints to be aware of:
- A "lead" is a synonym for contact. If the user is asking for a lead, they are asking for contact. Use this for figuring out the right functions to call.
- If the user asks to send an email to a hubspot contact, use the provided tools to send it via outlook, and then record the information in hubspot as an engagement email. 
- When you first start, don't explain everything you can do, just tell them generally what you can help them with and wait for instructions.
- If you're create things like deals, companies, or leads in hubspot, prompt the user for relevant fields.

```
its public on the gateway

**Comment by cjellick** [comment]
but if you dont have a hubspot account (most dont), the hubspot bit is not important to reproducing

**Comment by thedadams** [comment]
PR: https://github.com/gptscript-ai/desktop/pull/463

**Comment by sangee2004** [comment]
Tested with latest build from  `2be2f66601`

Able to chat with assistants that require multiple oath flows to succeed.

Tested with "Acorn Engineer" and the following assistant that requires multiple oauth flow.

![Image](https://github.com/user-attachments/assets/b5e4b011-1326-420f-b702-54472c3d6975)
