### ISSUE TITLE
We have bad horizontal scrolling behavior

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#461]
We have a horizontal scroll that is appearing and disappearing. THis looks realy bad. See video
https://www.loom.com/share/eb3c64f0db7c44dabc0660295bc337fe?sid=5ef03b30-de8b-41a9-adbc-0da97489439e

**Comment by cjellick** [comment]
Another issue: you can get double scrollbars
<img width="1208" alt="Screenshot 2024-09-07 at 12 44 41 PM" src="https://github.com/user-attachments/assets/8fc73c65-a307-42a1-9394-41449344d5ad">

**Comment by sangee2004** [comment]
Tested with electron build -`0f259cd7e`

https://github.com/user-attachments/assets/b3b5634b-2ee6-4e60-b09e-3ece744fc19c

https://github.com/user-attachments/assets/03a62b94-70dd-426c-9448-9a6816cd22e3
