### ISSUE TITLE
Errors seen when editing custom tool.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#482]
Tested with electron build - `e6f2a4aaa`

**Steps to reproduce the problem:**

1. Create an assistant
2. Click on "Create a toool"
3. On the new tool that gets created , click on "edit"

Following error is seen.
![Image](https://github.com/user-attachments/assets/6bd93d74-1a8e-45c6-8f73-55bf301e8869)

"Restart script" does not help.

**Comment by tylerslaton** [comment]
Working through this with Donnie as well.

**Comment by tylerslaton** [comment]
https://github.com/gptscript-ai/desktop/pull/493

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with electron build - `ceefbf85`

User is now presented with this message:
![Image](https://github.com/user-attachments/assets/5fdde459-250b-4720-9d91-2a7e9888262d)
