### ISSUE TITLE
UI - Make the entries for Adding tool from catalog/URL in `Chat view` and `Assistant Edit view` match.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#487]
Currently this is how we have :

In Chat view:
<img width="960" alt="Screenshot 2024-09-10 at 1 45 15 PM" src="https://github.com/user-attachments/assets/aeb35c67-d27e-4f2c-ac76-aee52710a022">

In Assistant Edit view:
<img width="555" alt="Screenshot 2024-09-10 at 1 44 55 PM" src="https://github.com/user-attachments/assets/e1746887-2368-4646-b65c-0be5ac441137">

Can we make the entries for Adding tool from catalog/URL in `Chat view` and `Assistant Edit view` to match ?

**Comment by cjellick** [comment]
not doing this.
