### ISSUE TITLE
Knowledge - Query about knowledge files do not work the first time but works when the query is made again.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#492]
Electron build - `18eaca7`

**Steps to reproduce the problem:**
1. Create an assistant with all Knowledge demo files (from onedrive) - https://github.com/gptscript-ai/desktop/issues/491
2. Chat with this assistant

I see that most of the the times , the first chat message always does not return any info for me.
Snippet of stack trace:
```
Chatted with MyKnowledgeAssistant
Input
"what is our parental leave policy"
Messages
* I can help you with that. If you have any documents or files related to your company's parental leave policy, you can upload them, and I can retrieve the information for you.
Calls
Loaded context from Knowledge Retrieval Context
```

But when i repeat the same query again, knowledgeRetrieval tool is called and it succeeded.

Snippet of stack trace:
```
Chatted with MyKnowledgeAssistant
Input
"What is our parental leave policy"
Messages
* <tool call> knowledgeRetrieval -> {"query":"parental leave policy"}
* The parental leave policy for your company is as follows: 1. **Eligibility**: Any full-time regular employee is eligible for ...
```

<img width="695" alt="Screenshot 2024-09-10 at 5 07 37 PM" src="https://github.com/user-attachments/assets/2000ea9c-c17a-4958-84d8-d8c527079abc">

**Comment by iwilltry42** [comment]
Hopefully the addition to the queryRelevancy input filter enhances the experience.
This will come into the desktop app via #526

**Comment by sangee2004** [comment]
Tested with build from `01bb57f3c6fc4`

This issue is not seen any more.
