### ISSUE TITLE
Can I edit a running assistant

### ISSUE THREAD

**Issue by sheng-liang** [gptscript-ai/desktop#66]
Can I transition from running an assistant to editing the assistant? Can I have an edit button when running my assistants?

**Comment by cjellick** [comment]
@thedadams I'm filing this under the work you are doing around "Save as.." and thus assigning to you.

**Comment by thedadams** [comment]
Using this issue for the basic "save as" functionality without knowledge.

That PR is here: https://github.com/gptscript-ai/desktop/pull/351

**Comment by thedadams** [comment]
The basic (without knowledge) save-as functionality is in.

There is another more comprehensive PR adding the knowledge stuff to this functionality.

**Comment by sangee2004** [comment]
Tested with latest build from ` 090c16f8a`
"Save Assistant" and "Save Assistant As" options are available and working as expected.
Other issues seen when testing this workflow will be logged a separate issues.

**Scenario 1:**

1. Chat with `Tildy`.
2. Add few tools  using "Add tool from catalog"
3. Have conversations relating to the tools that was added.
4. Use "Save Assistant As.." option to make a new assistant.
This results in a new assistant being created with tools added from step2 and current thread starts using this assistant.

5. Able to chat with the new assistant that was created in step4 with the tools that were added in step 2.


**Scenario 2:**
1. Create an assistant with some tools.
2. Chat this is assistant.
3. Add another tool to the thread using  "Add tool from catalog".
4. Use "Save Assistant" option.
This results in a new tools being added to the existing assistant.
