### ISSUE TITLE
Assistant editor needs a prominent "reload chat" button or needs to do it automatically

### ISSUE THREAD

**Issue by cjellick** [gptscript-ai/desktop#72]
It needs to be more obvious that the chat needs to reload to apply the changes happening on the left side editor

**Comment by sangee2004** [comment]
We are now presented with the following "Refresh Chat" button to indicate refresh is needed changes are made to the assistant.

![Image](https://github.com/user-attachments/assets/7ef1be12-c2d0-45c6-9287-bf07b0c1b86c)
