### ISSUE TITLE
UI - Allowed to add empty tools using "Add by URL"

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#74]
**Steps to reproduce the problem:**
1. Create an assistant.
2. Edit the assistant.
3. Use "Find tools" option and then "Add by URL" option to add a tool. 
4. Do not anter anything and click on "+" and close this page.

Notice that an empty tool gets added.
<img width="485" alt="Screenshot 2024-08-09 at 4 28 43 PM" src="https://github.com/user-attachments/assets/36245071-d911-43d7-b475-ad938e1de524">

**Expected Behavior:**
Should not add empty tool entry .

**Comment by sangee2004** [comment]
This issue is also seen when using "Add tool" option from Chat view and clicking on "+" sign without adding any content to the "Add by URL" option.

<img width="732" alt="Screenshot 2024-08-12 at 12 37 43 PM" src="https://github.com/user-attachments/assets/af6f4f6e-224b-428c-8890-48bd4fc69c9b">

**Comment by tylerslaton** [comment]
@sangee2004 This should now be fixed. You should see nothing happen if the input is empty.

**Comment by sangee2004** [comment]
Tested with version `0.10.0-rc2`. This issue is not seen anymore.
We are not allowed to add empty tools.
