### ISSUE TITLE
Not able to use "Add tools" to add tools that require oauth credential flow (outlook, notion tool)

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#80]
Electron build used -  `08213a013cc`

Make sure that you have not authenticated with outlook tool  already and you  dont have `outlook.mail.manage` credential.

**Steps to reproduce the problem:**
1. Chat with default assistant by going to `chat`
2. Use "Add tool" to add OutlookMail tool.
3. After this , notice that the chat gets stuck in "Loading your assistant..." page forever.

I see the following error message in console:

```
[98144:0812/134114.193114:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
```

**Note** - I was able to get `Add tool` to OutlookMail tool successfully when we are already authenticated with outlook tool  and have `outlook.mail.manage` credential.

Also I was able to go thru the outlook mail authentication process successfully when I chat with an assistant that has the outlook tool added to it.

**Comment by g-linville** [comment]
Reassigning to @njhale since he is working on this

**Comment by sangee2004** [comment]
This issue is not seen when testing desktop with commit id -`1eeb6f0161e`
