### ISSUE TITLE
Add ability to get logs from the desktop electron app

### ISSUE THREAD

**Issue by njhale** [gptscript-ai/desktop#84]
We want to be able to access logs for production builds of the desktop production app.

At minimum, logs should be written to files somewhere on the system where they can be accessed to help with debugging customer issues.

As a stretch goal, we also want to be able to view and export logs in the app itself.

**Comment by sangee2004** [comment]
Tested with electron build - `54ecc2c`


We now have the option to export logs from settings page: 

![Image](https://github.com/user-attachments/assets/9428ec0e-f0f3-4379-a79c-4518eee27f59)
