### ISSUE TITLE
UI - Not able to list more than 10 assistants in “select a script” dropdown.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#93]
gptscript version v0.0.0-dev+160a7334

**Steps to reproduce the problem:**
1. Launch UI -  `DISABLE_CACHE=true GATEWAY_URL=https://gateway-api.gptscript.ai gptscript --ui --disable-cache`
2. Make sure you have more than 10 assistants in the "Explore" view in which case you will see a "Load More" option.
3. Run any script to launch the thread view.
4. Use the `+` option to chat with assistants.
5. Notice that only 10 assistants are presented in the assistant list .

<img width="577" alt="Screenshot 2024-08-06 at 8 53 18 AM" src="https://github.com/user-attachments/assets/5035ba34-87be-41dc-b93e-4eeb43b98b12">

**Comment by thedadams** [comment]
This should be addressed.

**Comment by sangee2004** [comment]
With latest builds, I see all the assistants being listed but with no scroll bar

<img width="491" alt="Screenshot 2024-08-21 at 9 55 52 AM" src="https://github.com/user-attachments/assets/6f58b480-1236-402e-b2e1-9b4c3f4eb441">
 
But there is going to be an overhaul of what is going to be presented in this list. 

This is what we expect to be presented in this drop down:
```
Tildy
The first three of "My" assistants
A link to My Assistants (the Build page)
A link to Explore Assistants
```
