### ISSUE TITLE
UI - "MaxListenersExceededWarning" error encountered after which we UI becomes unresponsive.

### ISSUE THREAD

**Issue by sangee2004** [gptscript-ai/desktop#99]
Electron build from commit id - `e8c58e5aca2`

**Steps to reproduce the problem:**
**PreReq** - Have few assistant and chat threads

1. Create an assistant.
2. Chat this this assistant and say a thread called `thread1` gets crrated.
3. Delete this assistant.
4. Now select the thread that was created from step2.
5. This will result in the thread not loading and being stuck which is tracked in https://github.com/gptscript-ai/desktop/issues/96. 
6. When "loading script" is presented , Wait for 10 - 15 secs and then click on any other thread.
7. Once the this is thread is loaded , go back to the `thread1` from step2 .This will again result in being stuck in "loading script".
Following steps  6 and 7 couple of times , will result in even threads (that are from existing assistants) get struck in "loading script" state.

Once we reach this state, clicking on any other threads for about 10 times results in the following error seen and UI becomes completely unresponsive.

```
(node:34653) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 interrupt listeners added to [Socket]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(Use `Assistant Studio --trace-warnings ...` to show where the warning was created)
(node:34653) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 addTool listeners added to [Socket]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(node:34653) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 removeTool listeners added to [Socket]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
```

<img width="1406" alt="Screenshot 2024-08-08 at 11 33 31 AM" src="https://github.com/user-attachments/assets/fdeaa64a-4973-4400-b4a0-7083cb8d9f91">

**Comment by thedadams** [comment]
@sangee2004 I believe this has been addressed.

**Comment by sangee2004** [comment]
The workflow mentioned in the issue does not  reproduce any more when testing with `0.10.0-rc1` builds since access threads relating to deleted assistants are not stuck in loading state which was tracked in https://github.com/gptscript-ai/desktop/issues/96.

Closing this issue.
